/**
 * ML-DSA-44 原子块 Python 代码生成器
 * FIPS 204 final
 *
 * 内嵌完整 ML-DSA-44（单 ml_dsa_core() 闭包，内部所有辅助函数逐行取自已验证算法
 * mldsa_py_algo.py；常量在闭包顶部声明一次；SHAKE 用标准库 hashlib.shake_128/256）。
 * - ml_dsa_sign 确定性：rnd 缺省 = 0^32，ctx 缺省 = []（空上下文外部接口）
 * 官方向量：NIST ACVP sigGen ML-DSA-44 deterministic 30/30 PASS（external+internal）。
 */
import { pythonGenerator, Order } from 'blockly/python';
import type { Block } from 'blockly/core';

/** ML-DSA-44 完整实现（闭包：常量 + 全部辅助函数 + 入口，返回 dict） */
function registerMlDsaCore(): string {
  return pythonGenerator.provideFunction_('ml_dsa_core', [
    'def ' + pythonGenerator.FUNCTION_NAME_PLACEHOLDER_ + '():',
    '    import hashlib',
    '    Q = 8380417',
    '    N = 256',
    '    D = 13',
    '    TAU = 39',
    '    GAMMA1 = 1 << 17',
    '    GAMMA2 = (Q - 1) // 88',
    '    K = 4',
    '    L = 4',
    '    ETA = 2',
    '    BETA = TAU * ETA',
    '    OMEGA = 80',
    '    CTILDE_LEN = 32',
    '    ZETA = 1753',
    '    F_INTT = 8347681',
    '    MVAL = (Q - 1) // (2 * GAMMA2)',
    '    Q_HALF = Q // 2',
    '    def ml_dsa_mod(x):',
    '        return x % Q',
    '    def ml_dsa_centered(x):',
    '        x = x % Q',
    '        if x > Q_HALF:',
    '            x -= Q',
    '        return x',
    '    def ml_dsa_bitrev8(x):',
    '        r = 0',
    '        for _ in range(8):',
    '            r = (r << 1) | (x & 1)',
    '            x >>= 1',
    '        return r',
    '    def ml_dsa_shake(inp, out_len, rate):',
    '        """SHAKE256 (rate 136) / SHAKE128 (rate 168); returns list[int]."""',
    '        if isinstance(inp, str):',
    '            inp = inp.encode()',
    '        algo = \'shake_256\' if rate == 136 else \'shake_128\'',
    '        return list(getattr(hashlib, algo)(bytes(inp)).digest(out_len))',
    '    def ml_dsa_zetas():',
    '        z = [0] * 256',
    '        for k in range(1, 256):',
    '            z[k] = pow(1753, ml_dsa_bitrev8(k), 8380417)',
    '        return z',
    '    def ml_dsa_ntt(a):',
    '        a = [x % Q for x in a]',
    '        m = 0',
    '        length = 128',
    '        while length >= 1:',
    '            start = 0',
    '            while start < 256:',
    '                m += 1',
    '                z = ZETAS[m]',
    '                for j in range(start, start + length):',
    '                    t = z * a[j + length] % Q',
    '                    a[j + length] = (a[j] - t) % Q',
    '                    a[j] = (a[j] + t) % Q',
    '                start += 2 * length',
    '            length //= 2',
    '        return a',
    '    def ml_dsa_intt(a):',
    '        a = [x % Q for x in a]',
    '        m = 256',
    '        length = 1',
    '        while length < 256:',
    '            start = 0',
    '            while start < 256:',
    '                m -= 1',
    '                z = (-ZETAS[m]) % Q',
    '                for j in range(start, start + length):',
    '                    t = a[j]',
    '                    a[j] = (t + a[j + length]) % Q',
    '                    a[j + length] = (t - a[j + length]) % Q',
    '                    a[j + length] = z * a[j + length] % Q',
    '                start += 2 * length',
    '            length *= 2',
    '        return [(F_INTT * x) % Q for x in a]',
    '    def ml_dsa_mul_ntt(ai, bi):',
    '        return [ai[i] * bi[i] % Q for i in range(256)]',
    '    def ml_dsa_decompose(r):',
    '        rp = r % Q',
    '        r0 = rp % (2 * GAMMA2)',
    '        if r0 > GAMMA2:',
    '            r0 -= 2 * GAMMA2',
    '        if rp - r0 == Q - 1:',
    '            return 0, r0 - 1',
    '        return (rp - r0) // (2 * GAMMA2), r0',
    '    def ml_dsa_high_bits(r):',
    '        return ml_dsa_decompose(r)[0]',
    '    def ml_dsa_low_bits(r):',
    '        return ml_dsa_decompose(r)[1]',
    '    def ml_dsa_power2round(r):',
    '        rp = r % Q',
    '        r0 = rp % (1 << D)',
    '        if r0 > (1 << (D - 1)):',
    '            r0 -= 1 << D',
    '        return (rp - r0) >> D, r0',
    '    def ml_dsa_make_hint(z, r):',
    '        return 1 if ml_dsa_high_bits(r) != ml_dsa_high_bits((r + z) % Q) else 0',
    '    def ml_dsa_use_hint(h, r):',
    '        r1, r0 = ml_dsa_decompose(r)',
    '        if h == 1 and r0 > 0:',
    '            return (r1 + 1) % MVAL',
    '        if h == 1 and r0 <= 0:',
    '            return (r1 - 1) % MVAL',
    '        return r1',
    '    def ml_dsa_sample_in_ball(seed):',
    '        h = ml_dsa_shake(seed, 8, 136)',
    '        c = [0] * 256',
    '        buflen = 64',
    '        buf = ml_dsa_shake(seed, buflen, 136)',
    '        idx = 8',
    '        for i in range(256 - TAU, 256):',
    '            j = buf[idx]',
    '            idx += 1',
    '            while j > i:',
    '                if idx >= buflen:',
    '                    buflen *= 2',
    '                    buf = ml_dsa_shake(seed, buflen, 136)',
    '                j = buf[idx]',
    '                idx += 1',
    '            c[i] = c[j]',
    '            k = i + TAU - 256',
    '            c[j] = -1 if (h[k >> 3] >> (k & 7)) & 1 else 1',
    '        return c',
    '    def ml_dsa_rej_ntt_poly(seed):',
    '        a = []',
    '        buflen = 168',
    '        buf = ml_dsa_shake(seed, buflen, 168)  # SHAKE128',
    '        idx = 0',
    '        while len(a) < 256:',
    '            if idx + 3 > buflen:',
    '                buflen *= 2',
    '                buf = ml_dsa_shake(seed, buflen, 168)',
    '            b0, b1, b2 = buf[idx], buf[idx + 1], buf[idx + 2]',
    '            idx += 3',
    '            z = b0 | (b1 << 8) | ((b2 & 0x7F) << 16)',
    '            if z < Q:',
    '                a.append(z)',
    '        return a',
    '    def ml_dsa_rej_bounded_poly(seed):',
    '        a = []',
    '        buflen = 136',
    '        buf = ml_dsa_shake(seed, buflen, 136)  # SHAKE256',
    '        idx = 0',
    '        while len(a) < 256:',
    '            if idx >= buflen:',
    '                buflen *= 2',
    '                buf = ml_dsa_shake(seed, buflen, 136)',
    '            z = buf[idx]',
    '            idx += 1',
    '            n0 = z & 0x0F',
    '            n1 = z >> 4',
    '            if n0 < 15:',
    '                a.append(2 - (n0 % 5))',
    '            if n1 < 15 and len(a) < 256:',
    '                a.append(2 - (n1 % 5))',
    '        return a',
    '    def ml_dsa_expand_a(rho):',
    '        A = []',
    '        for r in range(K):',
    '            row = []',
    '            for s in range(L):',
    '                row.append(ml_dsa_rej_ntt_poly(rho + [s, r]))',
    '            A.append(row)',
    '        return A',
    '    def ml_dsa_expand_mask(rhop2, mu):',
    '        y = []',
    '        for r in range(L):',
    '            nonce = mu + r',
    '            seed = rhop2 + [nonce & 0xFF, (nonce >> 8) & 0xFF]',
    '            v = ml_dsa_shake(seed, 576, 136)',
    '            poly = []',
    '            for j in range(256):',
    '                pos = 18 * j',
    '                bo = pos >> 3',
    '                sh = pos & 7',
    '                t = (v[bo] | (v[bo + 1] << 8) | (v[bo + 2] << 16)) >> sh',
    '                t &= 0x3FFFF',
    '                poly.append(GAMMA1 - t)',
    '            y.append(poly)',
    '        return y',
    '    def ml_dsa_pack_bits(poly, bits, out_len, offset):',
    '        out = [0] * out_len',
    '        for j in range(256):',
    '            v = offset - poly[j]',
    '            for b in range(bits):',
    '                p = bits * j + b',
    '                out[p >> 3] |= ((v >> b) & 1) << (p & 7)',
    '        return out',
    '    def ml_dsa_unpack_bits(v, bits, offset):',
    '        poly = [0] * 256',
    '        for j in range(256):',
    '            t = 0',
    '            for b in range(bits):',
    '                p = bits * j + b',
    '                t |= ((v[p >> 3] >> (p & 7)) & 1) << b',
    '            poly[j] = offset - t',
    '        return poly',
    '    def ml_dsa_pack_18(zp):',
    '        return ml_dsa_pack_bits(zp, 18, 576, GAMMA1)',
    '    def ml_dsa_unpack_18(v):',
    '        return ml_dsa_unpack_bits(v, 18, GAMMA1)',
    '    def ml_dsa_pack_3(sp):',
    '        return ml_dsa_pack_bits(sp, 3, 96, ETA)',
    '    def ml_dsa_unpack_3(v):',
    '        return ml_dsa_unpack_bits(v, 3, ETA)',
    '    def ml_dsa_pack_13(t0p):',
    '        return ml_dsa_pack_bits(t0p, 13, 416, 1 << (D - 1))',
    '    def ml_dsa_unpack_13(v):',
    '        return ml_dsa_unpack_bits(v, 13, 1 << (D - 1))',
    '    def ml_dsa_pack_10_raw(poly):',
    '        out = [0] * 320',
    '        for j in range(256):',
    '            v = poly[j]',
    '            for b in range(10):',
    '                p = 10 * j + b',
    '                out[p >> 3] |= ((v >> b) & 1) << (p & 7)',
    '        return out',
    '    def ml_dsa_unpack_10_raw(v):',
    '        poly = [0] * 256',
    '        for j in range(256):',
    '            t = 0',
    '            for b in range(10):',
    '                p = 10 * j + b',
    '                t |= ((v[p >> 3] >> (p & 7)) & 1) << b',
    '            poly[j] = t',
    '        return poly',
    '    def ml_dsa_pack_6_raw(poly):',
    '        out = [0] * 192',
    '        for j in range(256):',
    '            v = poly[j]',
    '            for b in range(6):',
    '                p = 6 * j + b',
    '                out[p >> 3] |= ((v >> b) & 1) << (p & 7)',
    '        return out',
    '    def ml_dsa_unpack_6_raw(v):',
    '        poly = [0] * 256',
    '        for j in range(256):',
    '            t = 0',
    '            for b in range(6):',
    '                p = 6 * j + b',
    '                t |= ((v[p >> 3] >> (p & 7)) & 1) << b',
    '            poly[j] = t',
    '        return poly',
    '    def ml_dsa_hint_pack(h):',
    '        y = [0] * (OMEGA + K)',
    '        idx = 0',
    '        for i in range(K):',
    '            for j in range(256):',
    '                if h[i][j]:',
    '                    y[idx] = j',
    '                    idx += 1',
    '            y[OMEGA + i] = idx',
    '        return y',
    '    def ml_dsa_hint_unpack(y):',
    '        h = [[0] * 256 for _ in range(K)]',
    '        idx = 0',
    '        for i in range(K):',
    '            if y[OMEGA + i] < idx or y[OMEGA + i] > OMEGA:',
    '                return None',
    '            first = idx',
    '            while idx < y[OMEGA + i]:',
    '                if idx > first and y[idx - 1] >= y[idx]:',
    '                    return None',
    '                h[i][y[idx]] = 1',
    '                idx += 1',
    '        for i in range(idx, OMEGA):',
    '            if y[i] != 0:',
    '                return None',
    '        return h',
    '    def ml_dsa_sk_decode(sk):',
    '        rho = sk[0:32]',
    '        kk = sk[32:64]',
    '        tr = sk[64:128]',
    '        pos = 128',
    '        s1 = [ml_dsa_unpack_3(sk[pos + 96 * i:pos + 96 * (i + 1)]) for i in range(L)]',
    '        pos += 96 * L',
    '        s2 = [ml_dsa_unpack_3(sk[pos + 96 * i:pos + 96 * (i + 1)]) for i in range(K)]',
    '        pos += 96 * K',
    '        t0 = [ml_dsa_unpack_13(sk[pos + 416 * i:pos + 416 * (i + 1)]) for i in range(K)]',
    '        return rho, kk, tr, s1, s2, t0',
    '    def ml_dsa_pk_encode(rho, t1):',
    '        pk = rho[:]',
    '        for i in range(K):',
    '            pk += ml_dsa_pack_10_raw(t1[i])',
    '        return pk',
    '    def ml_dsa_pk_decode(pk):',
    '        rho = pk[0:32]',
    '        t1 = [ml_dsa_unpack_10_raw(pk[32 + 320 * i:32 + 320 * (i + 1)]) for i in range(K)]',
    '        return rho, t1',
    '    def ml_dsa_sig_encode(ctilde, z, h):',
    '        sig = ctilde[:]',
    '        for i in range(L):',
    '            sig += ml_dsa_pack_18(z[i])',
    '        sig += ml_dsa_hint_pack(h)',
    '        return sig',
    '    def ml_dsa_sig_decode(sig):',
    '        ctilde = sig[0:32]',
    '        pos = 32',
    '        z = [ml_dsa_unpack_18(sig[pos + 576 * i:pos + 576 * (i + 1)]) for i in range(L)]',
    '        pos += 576 * L',
    '        h = ml_dsa_hint_unpack(sig[pos:pos + OMEGA + K])',
    '        return ctilde, z, h',
    '    def ml_dsa_w1_encode(w1):',
    '        out = []',
    '        for r in range(K):',
    '            out += ml_dsa_pack_6_raw(w1[r])',
    '        return out',
    '    def ml_dsa_sign_internal(sk, mprime, rnd):',
    '        rho, kk, tr, s1, s2, t0 = ml_dsa_sk_decode(sk)',
    '        s1h = [ml_dsa_ntt(p) for p in s1]',
    '        s2h = [ml_dsa_ntt(p) for p in s2]',
    '        t0h = [ml_dsa_ntt(p) for p in t0]',
    '        A = ml_dsa_expand_a(rho)',
    '        mu = ml_dsa_shake(tr + mprime, 64, 136)',
    '        rhop2 = ml_dsa_shake(kk + rnd + mu, 64, 136)',
    '        kappa = 0',
    '        while True:',
    '            y = ml_dsa_expand_mask(rhop2, kappa)',
    '            yh = [ml_dsa_ntt(p) for p in y]',
    '            w = []',
    '            for r in range(K):',
    '                acc = [0] * 256',
    '                for s in range(L):',
    '                    pr = ml_dsa_mul_ntt(A[r][s], yh[s])',
    '                    acc = [(acc[i] + pr[i]) % Q for i in range(256)]',
    '                w.append(ml_dsa_intt(acc))',
    '            w1 = [[ml_dsa_high_bits(c) for c in w[r]] for r in range(K)]',
    '            ctilde = ml_dsa_shake(mu + ml_dsa_w1_encode(w1), CTILDE_LEN, 136)',
    '            c = ml_dsa_sample_in_ball(ctilde)',
    '            ch = ml_dsa_ntt(c)',
    '            cs1 = [ml_dsa_intt(ml_dsa_mul_ntt(ch, s1h[i])) for i in range(L)]',
    '            z = []',
    '            zmax = 0',
    '            for i in range(L):',
    '                zp = []',
    '                for j in range(256):',
    '                    zv = ml_dsa_centered(y[i][j] + cs1[i][j])',
    '                    zp.append(zv)',
    '                    zmax = max(zmax, abs(zv))',
    '                z.append(zp)',
    '            cs2 = [ml_dsa_intt(ml_dsa_mul_ntt(ch, s2h[i])) for i in range(K)]',
    '            r0max = 0',
    '            for r in range(K):',
    '                for j in range(256):',
    '                    lv = ml_dsa_low_bits((w[r][j] - cs2[r][j]) % Q)',
    '                    r0max = max(r0max, abs(lv))',
    '            if zmax >= GAMMA1 - BETA or r0max >= GAMMA2 - BETA:',
    '                kappa += L',
    '                continue',
    '            ct0 = [ml_dsa_intt(ml_dsa_mul_ntt(ch, t0h[i])) for i in range(K)]',
    '            h = []',
    '            weight = 0',
    '            ct0max = 0',
    '            for r in range(K):',
    '                hr = []',
    '                for j in range(256):',
    '                    ct = ml_dsa_centered(ct0[r][j])',
    '                    ct0max = max(ct0max, abs(ct))',
    '                    base = (w[r][j] - cs2[r][j] + ct0[r][j]) % Q',
    '                    bit = ml_dsa_make_hint((-ct) % Q, base)',
    '                    hr.append(bit)',
    '                    weight += bit',
    '                h.append(hr)',
    '            if ct0max >= GAMMA2 or weight > OMEGA:',
    '                kappa += L',
    '                continue',
    '            break',
    '        return ml_dsa_sig_encode(ctilde, z, h)',
    '    def ml_dsa_sign(sk, message, ctx=None, rnd=None):',
    '        if ctx is None:',
    '            ctx = []',
    '        if rnd is None:',
    '            rnd = [0] * 32',
    '        mprime = [0x00, len(ctx)] + list(ctx) + list(message)',
    '        return ml_dsa_sign_internal(sk, mprime, rnd)',
    '    def ml_dsa_verify_internal(pk, mprime, sig):',
    '        rho, t1 = ml_dsa_pk_decode(pk)',
    '        ctilde, z, h = ml_dsa_sig_decode(sig)',
    '        if h is None:',
    '            return False',
    '        if sum(sum(p) for p in h) > OMEGA:',
    '            return False',
    '        A = ml_dsa_expand_a(rho)',
    '        tr = ml_dsa_shake(pk, 64, 136)',
    '        mu = ml_dsa_shake(tr + mprime, 64, 136)',
    '        c = ml_dsa_sample_in_ball(ctilde)',
    '        ch = ml_dsa_ntt(c)',
    '        zh = [ml_dsa_ntt(p) for p in z]',
    '        t1h = [ml_dsa_ntt(p) for p in t1]',
    '        wapprox = []',
    '        for r in range(K):',
    '            acc = [0] * 256',
    '            for s in range(L):',
    '                pr = ml_dsa_mul_ntt(A[r][s], zh[s])',
    '                acc = [(acc[i] + pr[i]) % Q for i in range(256)]',
    '            t2d = [(t1h[r][i] * (1 << D)) % Q for i in range(256)]',
    '            pr2 = ml_dsa_mul_ntt(ch, t2d)',
    '            acc = [(acc[i] - pr2[i]) % Q for i in range(256)]',
    '            wapprox.append(ml_dsa_intt(acc))',
    '        w1 = [[ml_dsa_use_hint(h[r][j], wapprox[r][j]) for j in range(256)] for r in range(K)]',
    '        ctilde2 = ml_dsa_shake(mu + ml_dsa_w1_encode(w1), CTILDE_LEN, 136)',
    '        zmax = max(max(abs(v) for v in p) for p in z)',
    '        return ctilde2 == ctilde and zmax < GAMMA1 - BETA',
    '    def ml_dsa_verify(pk, message, sig, ctx=None):',
    '        if ctx is None:',
    '            ctx = []',
    '        mprime = [0x00, len(ctx)] + list(ctx) + list(message)',
    '        return ml_dsa_verify_internal(pk, mprime, sig)',
    '    def ml_dsa_pk_from_sk(sk):',
    '        rho, kk, tr, s1, s2, t0 = ml_dsa_sk_decode(sk)',
    '        A = ml_dsa_expand_a(rho)',
    '        s1h = [ml_dsa_ntt(p) for p in s1]',
    '        t = []',
    '        for r in range(K):',
    '            acc = [0] * 256',
    '            for s in range(L):',
    '                pr = ml_dsa_mul_ntt(A[r][s], s1h[s])',
    '                acc = [(acc[i] + pr[i]) % Q for i in range(256)]',
    '            acc = ml_dsa_intt(acc)',
    '            acc = [(acc[i] + s2[r][i]) % Q for i in range(256)]',
    '            t.append(acc)',
    '        t1 = [[ml_dsa_power2round(c)[0] for c in t[r]] for r in range(K)]',
    '        return ml_dsa_pk_encode(rho, t1)',
    '    ZETAS = ml_dsa_zetas()',
    '    return {\'sign\': ml_dsa_sign, \'verify\': ml_dsa_verify, \'sign_internal\': ml_dsa_sign_internal, \'verify_internal\': ml_dsa_verify_internal, \'pk_from_sk\': ml_dsa_pk_from_sk}',
    '',
  ]);
}

/** 公共签名入口：ml_dsa_sign(sk, message, ctx?, rnd?) — 缺省 ctx=[], rnd=0^32 */
function registerMlDsaSign(): string {
  const core = registerMlDsaCore();
  registerMlDsaSignInternal();
  registerMlDsaVerifyInternal();
  registerMlDsaPkFromSk();
  return pythonGenerator.provideFunction_('ml_dsa_sign', [
    'def ' + pythonGenerator.FUNCTION_NAME_PLACEHOLDER_ + '(sk, message, ctx=None, rnd=None):',
    '    return ' + core + "()['sign'](sk, message, ctx, rnd)",
  ]);
}

/** 公共验签入口：ml_dsa_verify(pk, message, sig, ctx?) */
function registerMlDsaVerify(): string {
  const core = registerMlDsaCore();
  registerMlDsaSignInternal();
  registerMlDsaVerifyInternal();
  return pythonGenerator.provideFunction_('ml_dsa_verify', [
    'def ' + pythonGenerator.FUNCTION_NAME_PLACEHOLDER_ + '(pk, message, sig, ctx=None):',
    '    return ' + core + "()['verify'](pk, message, sig, ctx)",
  ]);
}

/** 公钥派生（测试/demo 用）：ml_dsa_pk_from_sk(sk) */
function registerMlDsaPkFromSk(): string {
  const core = registerMlDsaCore();
  return pythonGenerator.provideFunction_('ml_dsa_pk_from_sk', [
    'def ' + pythonGenerator.FUNCTION_NAME_PLACEHOLDER_ + '(sk):',
    '    return ' + core + "()['pk_from_sk'](sk)",
  ]);
}

/** 内部接口签名（ACVP internal 测试用）：ml_dsa_sign_internal(sk, mprime, rnd) */
function registerMlDsaSignInternal(): string {
  const core = registerMlDsaCore();
  return pythonGenerator.provideFunction_('ml_dsa_sign_internal', [
    'def ' + pythonGenerator.FUNCTION_NAME_PLACEHOLDER_ + '(sk, mprime, rnd):',
    '    return ' + core + "()['sign_internal'](sk, mprime, rnd)",
  ]);
}

/** 内部接口验签（ACVP internal 测试用）：ml_dsa_verify_internal(pk, mprime, sig) */
function registerMlDsaVerifyInternal(): string {
  const core = registerMlDsaCore();
  return pythonGenerator.provideFunction_('ml_dsa_verify_internal', [
    'def ' + pythonGenerator.FUNCTION_NAME_PLACEHOLDER_ + '(pk, mprime, sig):',
    '    return ' + core + "()['verify_internal'](pk, mprime, sig)",
  ]);
}

pythonGenerator.forBlock['mldsa_sign'] = function (block: Block): [string, number] {
  const sk = pythonGenerator.valueToCode(block, 'SECRET_KEY', Order.ATOMIC) || '[]';
  const msg = pythonGenerator.valueToCode(block, 'MESSAGE', Order.ATOMIC) || '[]';
  const fn = registerMlDsaSign();
  return [fn + '(' + sk + ', ' + msg + ')', Order.ATOMIC];
};

pythonGenerator.forBlock['mldsa_verify'] = function (block: Block): [string, number] {
  const pk = pythonGenerator.valueToCode(block, 'PUBLIC_KEY', Order.ATOMIC) || '[]';
  const msg = pythonGenerator.valueToCode(block, 'MESSAGE', Order.ATOMIC) || '[]';
  const sig = pythonGenerator.valueToCode(block, 'SIGNATURE', Order.ATOMIC) || '[]';
  const fn = registerMlDsaVerify();
  return [fn + '(' + pk + ', ' + msg + ', ' + sig + ')', Order.ATOMIC];
};
