/**
 * SM2 数字签名原子块 Python 代码生成器
 * GB/T 32918.2-2016（附录 A 示例 1，Fp-256 测试曲线）
 *
 * 内嵌全套（一次 provideFunction_ 注册去重）：
 *   sm3_hash  —— 与 remaining.ts hash_hmac SM3 分支同体（GB/T 32905）
 *   sm2_za    —— ZA = SM3(ENTLA ‖ IDA ‖ a ‖ b ‖ Gx ‖ Gy ‖ PAx ‖ PAy)
 *   sm2_sign  —— e = SM3(ZA ‖ M)；r/s 公式；输出 r‖s 各 32 字节大端
 *   sm2_verify —— t = (r+s) mod n，[s]G + [t]PA，R = (e + x0') mod n == r
 * 原生 int + pow(a,-1,m) 模逆。官方向量 ZA/e/r/s 全 PASS。
 */
import { pythonGenerator, Order } from 'blockly/python';
import type { Block } from 'blockly/core';

/** SM2 全套内嵌函数（sm3_hash/sm2_za/sm2_sign/sm2_verify 均在模块作用域，driver 可直接调用） */
function registerSm2(): string {
  return pythonGenerator.provideFunction_('sm2_sign', [
    'def sm3_hash(input):',
    '    if isinstance(input, str):',
    '        input = input.encode("utf-8")',
    '    m = list(input)',
    '    m_len_bits = len(m) * 8',
    '    kk = (448 - m_len_bits - 1) % 512',
    '    if kk < 0:',
    '        kk += 512',
    '    m = m + [0x80] + [0] * (kk // 8) + [0] * 8',
    '    for i in range(4):',
    '        m[-1 - i] = (m_len_bits >> (8 * i)) & 0xFF',
    '    def rotl(x, n):',
    '        return ((x << n) | (x >> (32 - n))) & 0xFFFFFFFF',
    '    def p0(x):',
    '        return x ^ rotl(x, 9) ^ rotl(x, 17)',
    '    def p1(x):',
    '        return x ^ rotl(x, 15) ^ rotl(x, 23)',
    '    IV = [0x7380166F, 0x4914B2B9, 0x172442D7, 0xDA8A0600, 0xA96F30BC, 0x163138AA, 0xE38DEE4D, 0xB0FB0E4E]',
    '    v = list(IV)',
    '    for off in range(0, len(m), 64):',
    '        b = m[off:off + 64]',
    '        w = [0] * 68',
    '        for j in range(16):',
    '            w[j] = (b[j * 4] << 24) | (b[j * 4 + 1] << 16) | (b[j * 4 + 2] << 8) | b[j * 4 + 3]',
    '        for j in range(16, 68):',
    '            w[j] = (p1(w[j - 16] ^ w[j - 9] ^ rotl(w[j - 3], 15)) ^ rotl(w[j - 13], 7) ^ w[j - 6]) & 0xFFFFFFFF',
    '        a, b2, c, d, e, f, g, h = v',
    '        for j in range(64):',
    '            if j < 16:',
    '                ff = a ^ b2 ^ c',
    '                gg = e ^ f ^ g',
    '                t = 0x79CC4519',
    '            else:',
    '                ff = (a & b2) | (a & c) | (b2 & c)',
    '                gg = (e & f) | ((~e) & g)',
    '                t = 0x7A879D8A',
    '            ss1 = rotl((rotl(a, 12) + e + rotl(t, j % 32)) & 0xFFFFFFFF, 7)',
    '            ss2 = ss1 ^ rotl(a, 12)',
    '            tt1 = (ff + d + ss2 + (w[j] ^ w[j + 4])) & 0xFFFFFFFF',
    '            tt2 = (gg + h + ss1 + w[j]) & 0xFFFFFFFF',
    '            d = c',
    '            c = rotl(b2, 9)',
    '            b2 = a',
    '            a = tt1',
    '            h = g',
    '            g = rotl(f, 19)',
    '            f = e',
    '            e = p0(tt2)',
    '        v = [(x ^ y) & 0xFFFFFFFF for x, y in zip(v, [a, b2, c, d, e, f, g, h])]',
    '    out = []',
    '    for x in v:',
    '        out += [(x >> 24) & 0xFF, (x >> 16) & 0xFF, (x >> 8) & 0xFF, x & 0xFF]',
    '    return out',
    '',
    'def sm2_params():',
    '    return {',
    '        "p": 0x8542D69E4C044F18E8B92435BF6FF7DE457283915C45517D722EDB8B08F1DFC3,',
    '        "a": 0x787968B4FA32C3FD2417842E73BBFEFF2F3C848B6831D7E0EC65228B3937E498,',
    '        "b": 0x63E4C6D3B23B0C849CF84241484BFE48F61D59A5B16BA06E6E12D1DA27C5249A,',
    '        "n": 0x8542D69E4C044F18E8B92435BF6FF7DD297720630485628D5AE74EE7C32E79B7,',
    '        "gx": 0x421DEBD61B62EAB6746434EBC3CC315E32220B3BADD50BDC4C4E6C147FEDD43D,',
    '        "gy": 0x0680512BCBB42C07D47349D2153B70C4E5D7FDFCBFA36EA1A85841B9E46E09A2,',
    '    }',
    '',
    'def sm2_to_big(v):',
    '    if isinstance(v, int):',
    '        return v',
    '    if isinstance(v, str):',
    '        return int(v, 16)',
    '    return int.from_bytes(bytes(v), "big")',
    '',
    'def sm2_big_to_bytes(x, length):',
    '    return [(x >> (8 * (length - 1 - i))) & 0xFF for i in range(length)]',
    '',
    'def sm2_mod_inverse(a, m):',
    '    return pow(a % m, -1, m)',
    '',
    'def sm2_point_double(P):',
    '    C = sm2_params()',
    '    if P is None or P[1] == 0:',
    '        return None',
    '    lam = ((3 * P[0] * P[0] + C["a"]) * sm2_mod_inverse(2 * P[1], C["p"])) % C["p"]',
    '    x3 = (lam * lam - 2 * P[0]) % C["p"]',
    '    y3 = (lam * (P[0] - x3) - P[1]) % C["p"]',
    '    return (x3, y3)',
    '',
    'def sm2_point_add(P, Q):',
    '    C = sm2_params()',
    '    if P is None:',
    '        return Q',
    '    if Q is None:',
    '        return P',
    '    if P[0] == Q[0]:',
    '        if (P[1] + Q[1]) % C["p"] == 0:',
    '            return None',
    '        return sm2_point_double(P)',
    '    lam = ((Q[1] - P[1]) * sm2_mod_inverse((Q[0] - P[0]) % C["p"], C["p"])) % C["p"]',
    '    x3 = (lam * lam - P[0] - Q[0]) % C["p"]',
    '    y3 = (lam * (P[0] - x3) - P[1]) % C["p"]',
    '    return (x3, y3)',
    '',
    'def sm2_point_mul(k, P):',
    '    R = None',
    '    Q = P',
    '    while k > 0:',
    '        if k & 1:',
    '            R = sm2_point_add(R, Q)',
    '        Q = sm2_point_double(Q)',
    '        k >>= 1',
    '    return R',
    '',
    'def sm2_za(ida, pax, pay):',
    '    C = sm2_params()',
    '    if isinstance(ida, str):',
    '        ida_bytes = ida.encode("utf-8")',
    '    else:',
    '        ida_bytes = bytes(ida)',
    '    entla = len(ida_bytes) * 8',
    '    z = [(entla >> 8) & 0xFF, entla & 0xFF]',
    '    z += list(ida_bytes)',
    '    z += sm2_big_to_bytes(C["a"], 32) + sm2_big_to_bytes(C["b"], 32)',
    '    z += sm2_big_to_bytes(C["gx"], 32) + sm2_big_to_bytes(C["gy"], 32)',
    '    z += sm2_big_to_bytes(sm2_to_big(pax), 32) + sm2_big_to_bytes(sm2_to_big(pay), 32)',
    '    return sm3_hash(z)',
    '',
    'def ' + pythonGenerator.FUNCTION_NAME_PLACEHOLDER_ + '(da, ida, msg, k):',
    '    C = sm2_params()',
    '    d = sm2_to_big(da)',
    '    if d <= 0 or d >= C["n"]:',
    '        raise ValueError("SM2: invalid private key")',
    '    PA = sm2_point_mul(d, (C["gx"], C["gy"]))',
    '    za = sm2_za(ida, PA[0], PA[1])',
    '    e = sm2_to_big(sm3_hash(za + list(msg)))',
    '    if k is None or k == "":',
    '        import os',
    '        kk = sm2_to_big(os.urandom(32))',
    '    else:',
    '        kk = sm2_to_big(k)',
    '    kk %= C["n"]',
    '    if kk == 0:',
    '        kk = 1',
    '    x1 = sm2_point_mul(kk, (C["gx"], C["gy"]))',
    '    r = (e + x1[0]) % C["n"]',
    '    s = (sm2_mod_inverse(1 + d, C["n"]) * ((kk - r * d) % C["n"])) % C["n"]',
    '    if r == 0 or r + kk == C["n"] or s == 0:',
    '        raise ValueError("SM2: retry (r or s invalid)")',
    '    return sm2_big_to_bytes(r, 32) + sm2_big_to_bytes(s, 32)',
    '',
    'def sm2_verify(pax, pay, ida, msg, r, s):',
    '    C = sm2_params()',
    '    rr = sm2_to_big(r) % C["n"]',
    '    ss = sm2_to_big(s) % C["n"]',
    '    if rr == 0 or rr >= C["n"] or ss == 0 or ss >= C["n"]:',
    '        return False',
    '    t = (rr + ss) % C["n"]',
    '    if t == 0:',
    '        return False',
    '    za = sm2_za(ida, pax, pay)',
    '    e = sm2_to_big(sm3_hash(za + list(msg)))',
    '    G = (C["gx"], C["gy"])',
    '    PA = (sm2_to_big(pax), sm2_to_big(pay))',
    '    pt = sm2_point_add(sm2_point_mul(ss, G), sm2_point_mul(t, PA))',
    '    if pt is None:',
    '        return False',
    '    return (e + pt[0]) % C["n"] == rr',
    '',
  ]);
}

pythonGenerator.forBlock['sm2_sign'] = function (block: Block): [string, number] {
  const da = pythonGenerator.valueToCode(block, 'DA', Order.ATOMIC) || '""';
  const ida = pythonGenerator.valueToCode(block, 'IDA', Order.ATOMIC) || '""';
  const msg = pythonGenerator.valueToCode(block, 'MSG', Order.ATOMIC) || '[]';
  const k = pythonGenerator.valueToCode(block, 'K', Order.ATOMIC) || '""';
  registerSm2();
  return ['sm2_sign(' + da + ', ' + ida + ', ' + msg + ', ' + k + ')', Order.ATOMIC];
};

pythonGenerator.forBlock['sm2_verify'] = function (block: Block): [string, number] {
  const pax = pythonGenerator.valueToCode(block, 'PAX', Order.ATOMIC) || '""';
  const pay = pythonGenerator.valueToCode(block, 'PAY', Order.ATOMIC) || '""';
  const ida = pythonGenerator.valueToCode(block, 'IDA', Order.ATOMIC) || '""';
  const msg = pythonGenerator.valueToCode(block, 'MSG', Order.ATOMIC) || '[]';
  const r = pythonGenerator.valueToCode(block, 'R', Order.ATOMIC) || '""';
  const s = pythonGenerator.valueToCode(block, 'S', Order.ATOMIC) || '""';
  registerSm2();
  return ['sm2_verify(' + pax + ', ' + pay + ', ' + ida + ', ' + msg + ', ' + r + ', ' + s + ')', Order.ATOMIC];
};
