/**
 * SM9 数字签名原子块 Python 代码生成器
 * GB/T 38635.2-2020（R-ate pairing，BN 曲线，Fp12 塔域 u²=-2, s³=u, t²=s）
 *
 * 内嵌全套（一次 provideFunction_ 注册去重）：ref_sm9.py 类结构转写，
 * 全部符号加 sm9/SM9 前缀防与其它生成器冲突。SM3 走 hashlib + 纯 Python 兜底。
 * 入口 sm9_master_key/sm9_user_key/sm9_sign/sm9_verify（模块作用域，driver 可直接调用）。
 * 官方向量（GB/T 38635.2-2020 附录 A.2：ks=0130E784…/IDA=Alice/hid=01/
 * M="Chinese IBS standard"/r=033c8616…）H/S/verify 全 PASS；与 Go gmsm 输出一致。
 */
import { pythonGenerator, Order } from 'blockly/python';
import type { Block } from 'blockly/core';

/** SM9 全套内嵌函数（常数/塔域/配对/四入口均在模块作用域，driver 可直接调用） */
function registerSm9(): string {
  return pythonGenerator.provideFunction_('sm9_sign', [
    'import hashlib',
    '',
    '# ---------- curve constants (GB/T 38635.1-2020 / GM/T 0044.1-2016) ----------',
    'SM9P = 0xb640000002a3a6f1d603ab4ff58ec74521f2934b1a7aeedbe56f9b27e351457d',
    'SM9N = 0xb640000002a3a6f1d603ab4ff58ec74449f2934b18ea8beee56ee19cd69ecf25  # group order r',
    '',
    'SM9_P1 = (',
    '    0x93de051d62bf718ff5ed0704487d01d6e1e4086909dc3280e8c4e4817c66dddd,',
    '    0x21fe8dda4f21e607631065125c395bbc1c1c00cbfa6024350c464cd70a3ea616,',
    ')',
    'SM9_P2 = (',
    '    (0x85aef3d078640c98597b6027b441a01ff1dd2c190f5e93c454806c11d8806141,',
    '     0x3722755292130b08d2aab97fd34ec120ee265948d19c17abf9b7213baf82d65b),',
    '    (0x17509b092e845c1266ba0d262cbee6ed0736a96fa347c8bd856dc76b84ebeb96,',
    '     0xa7cf28d519be3da65f3170153d278ff247efba98a71a08116215bba5c999a7c7),',
    ')',
    '',
    '# Frobenius constants (from gmsm constants.go)',
    'SM9_FROB_CONST = 0x3f23ea58e5720bdb843c6cfa9c08674947c5c86e0ddd04eda91d8354377b698b',
    'SM9_S_TO_P_MINUS_1 = 0x0000000000000000f300000002a3a6f2780272354f8b78f4d5fc11967be65334',
    'SM9_S_TO_2P_MINUS_2 = 0x0000000000000000f300000002a3a6f2780272354f8b78f4d5fc11967be65333',
    'SM9_S_TO_P2_MINUS_1 = SM9_S_TO_2P_MINUS_2',
    'SM9_S_TO_2P2_MINUS_2 = 0xb640000002a3a6f0e303ab4ff2eb2052a9f02115caef75e70f738991676af249',
    'SM9_BETA_NEG_PP1_O3 = 0xb640000002a3a6f0e303ab4ff2eb2052a9f02115caef75e70f738991676af24a',
    'SM9_BETA_NEG_PP1_O2 = 0x49db721a269967c4e0a8debc0783182f82555233139e9d63efbd7b54092c756c',
    'SM9_BETA_NEG_P2P1_O3 = SM9_S_TO_2P2_MINUS_2',
    'SM9_BETA_NEG_P2P1_O2 = 0xb640000002a3a6f1d603ab4ff58ec74521f2934b1a7aeedbe56f9b27e351457c',
    '',
    '# NAF encoding of 6u+2 (index 0 = LSB)',
    'SM9_NAF_6U2 = [0, -1, 0, 0, 0, 0, 1, 0, 1, 0, 0, -1, 0, -1, 0, 0, 0, -1, 0, -1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1]',
    '',
    'def sm9_sm3(data: bytes) -> bytes:',
    '    return hashlib.new(\'sm3\', data).digest() if \'sm3\' in hashlib.algorithms_available else sm9_sm3_py(data)',
    '',
    '# pure python SM3 fallback (identical to hashlib for these inputs)',
    'def sm9_sm3_py(data: bytes) -> bytes:',
    '    IV = [0x7380166f, 0x4914b2b9, 0x172442d7, 0xda8a0600, 0xa96f30bc, 0x163138aa, 0xe38dee4d, 0xb0fb0e4e]',
    '    def rotl(x, n): return ((x << n) | (x >> (32 - n))) & 0xFFFFFFFF',
    '    def p0(x): return x ^ rotl(x, 9) ^ rotl(x, 17)',
    '    def p1(x): return x ^ rotl(x, 15) ^ rotl(x, 23)',
    '    m = bytearray(data)',
    '    mlen = len(m) * 8',
    '    m.append(0x80)',
    '    while (len(m) * 8) % 512 != 448:',
    '        m.append(0)',
    '    m += mlen.to_bytes(8, \'big\')',
    '    v = list(IV)',
    '    for off in range(0, len(m), 64):',
    '        b = m[off:off+64]',
    '        w = [0]*68',
    '        for j in range(16):',
    '            w[j] = (b[j*4] << 24) | (b[j*4+1] << 16) | (b[j*4+2] << 8) | b[j*4+3]',
    '        for j in range(16, 68):',
    '            w[j] = (p1(w[j-16] ^ w[j-9] ^ rotl(w[j-3], 15)) ^ rotl(w[j-13], 7) ^ w[j-6]) & 0xFFFFFFFF',
    '        a, bb, c, d, e, f, g, h = v',
    '        for j in range(64):',
    '            if j < 16:',
    '                ff = a ^ bb ^ c; gg = e ^ f ^ g; t = 0x79cc4519',
    '            else:',
    '                ff = (a & bb) | (a & c) | (bb & c); gg = (e & f) | ((~e) & g); t = 0x7a879d8a',
    '            ss1 = rotl((rotl(a, 12) + e + rotl(t, j % 32)) & 0xFFFFFFFF, 7)',
    '            ss2 = ss1 ^ rotl(a, 12)',
    '            tt1 = (ff + d + ss2 + (w[j] ^ w[j+4])) & 0xFFFFFFFF',
    '            tt2 = (gg + h + ss1 + w[j]) & 0xFFFFFFFF',
    '            d = c; c = rotl(bb, 9); bb = a; a = tt1',
    '            h = g; g = rotl(f, 19); f = e; e = p0(tt2)',
    '        v = [(x ^ y) & 0xFFFFFFFF for x, y in zip(v, [a, bb, c, d, e, f, g, h])]',
    '    out = b\'\'',
    '    for x in v:',
    '        out += x.to_bytes(4, \'big\')',
    '    return out',
    '',
    '# ---------- H1/H2 (gmsm internal/sm9 hash: (Hv mod (N-1)) + 1) ----------',
    'def sm9_hash_h(z: bytes, mode: int) -> int:',
    '    ha = b\'\'',
    '    for ct in (1, 2):',
    '        ha += sm9_sm3(bytes([mode]) + z + ct.to_bytes(4, \'big\'))',
    '    return (int.from_bytes(ha[:40], \'big\') % (SM9N - 1)) + 1',
    '',
    'def sm9_H1(z: bytes) -> int:',
    '    return sm9_hash_h(z, 0x01)',
    '',
    'def sm9_H2(z: bytes) -> int:',
    '    return sm9_hash_h(z, 0x02)',
    '',
    '# ---------- Fp / Fp2 / Fp6 / Fp12 (b6 tower: u²=-2, s³=u, t²=s) ----------',
    'class SM9_F2:',
    '    """(x, y) = x·u + y"""',
    '    __slots__ = (\'x\', \'y\')',
    '    def __init__(self, x=0, y=0): self.x, self.y = x % SM9P, y % SM9P',
    '    def __add__(self, o): return SM9_F2(self.x + o.x, self.y + o.y)',
    '    def __sub__(self, o): return SM9_F2(self.x - o.x, self.y - o.y)',
    '    def __neg__(self): return SM9_F2(-self.x, -self.y)',
    '    def conj(self): return SM9_F2(-self.x, self.y)',
    '    def mul(self, o):',
    '        # (a0+a1u)(b0+b1u): u-coeff = a0b1+a1b0, const = a0b0-2a1b1',
    '        return SM9_F2(self.y * o.x + self.x * o.y, self.y * o.y - 2 * self.x * o.x)',
    '    def mul_u(self, o):',
    '        # (a0+a1u)(b0+b1u)·u: u-coeff = a0b0-2a1b1, const = -2(a0b1+a1b0)',
    '        return SM9_F2(self.y * o.y - 2 * self.x * o.x, -2 * (self.x * o.y + self.y * o.x))',
    '    def mul_u1(self):',
    '        # a·u: u-coeff = a0 (const), const = -2·a1 (u-coeff)',
    '        return SM9_F2(self.y, -2 * self.x)',
    '    def sqr(self):',
    '        return SM9_F2(2 * self.x * self.y, self.y * self.y - 2 * self.x * self.x)',
    '    def sqr_u(self):',
    '        # (xu+y)²·u = (y²-2x²)·u - 4xy',
    '        return SM9_F2(self.y * self.y - 2 * self.x * self.x, -4 * self.x * self.y)',
    '    def mul_scalar(self, k): return SM9_F2(self.x * k, self.y * k)',
    '    def inv(self):',
    '        # 1/(2x²+y²) · (-x·u + y)',
    '        inv = pow((2 * self.x * self.x + self.y * self.y) % SM9P, SM9P - 2, SM9P)',
    '        return SM9_F2(-self.x * inv, self.y * inv)',
    '    def frob(self):',
    '        # (xu+y)^p = -x·u + y',
    '        return SM9_F2(-self.x, self.y)',
    '    def is_zero(self): return self.x == 0 and self.y == 0',
    '    def is_one(self): return self.x == 0 and self.y == 1',
    '    def __eq__(self, o): return self.x == o.x and self.y == o.y',
    '    def __repr__(self): return f\'({self.x:x},{self.y:x})\'',
    '    @staticmethod',
    '    def one(): return SM9_F2(0, 1)',
    '    @staticmethod',
    '    def zero(): return SM9_F2(0, 0)',
    '',
    'class SM9_F6:',
    '    """(x, y, z) = x·s² + y·s + z, s³ = u"""',
    '    __slots__ = (\'x\', \'y\', \'z\')',
    '    def __init__(self, x=None, y=None, z=None):',
    '        self.x = x if x is not None else SM9_F2()',
    '        self.y = y if y is not None else SM9_F2()',
    '        self.z = z if z is not None else SM9_F2()',
    '    def __add__(self, o): return SM9_F6(self.x + o.x, self.y + o.y, self.z + o.z)',
    '    def __sub__(self, o): return SM9_F6(self.x - o.x, self.y - o.y, self.z - o.z)',
    '    def __neg__(self): return SM9_F6(-self.x, -self.y, -self.z)',
    '    def mul(self, o):',
    '        # (z0+y0 s+x0 s²)(z1+y1 s+x1 s²):',
    '        #  z = z0z1 + (y0x1+x0y1)·u ; y = z0y1+y0z1+x0x1·u ; x = z0x1+y0y1+x0z1',
    '        v0 = self.z.mul(o.z); v1 = self.y.mul(o.y); v2 = self.x.mul(o.x)',
    '        t = (self.y + self.x).mul(o.y + o.x) - v1 - v2',
    '        z = t.mul_u1() + v0',
    '        t = (self.z + self.y).mul(o.z + o.y) - v0 - v1',
    '        y = t + v2.mul_u1()',
    '        t = (self.z + self.x).mul(o.z + o.x) - v0 + v1',
    '        x = t - v2',
    '        return SM9_F6(x, y, z)',
    '    def mul_s(self):',
    '        # (z + y s + x s²)·s = y s² + z s + x·u',
    '        return SM9_F6(self.y, self.z, SM9_F2(self.x.y, -2 * self.x.x))',
    '    def sqr(self):',
    '        # (z² + 2xy·u) + (u·x² + 2yz)s + (y² + 2xz)s²',
    '        v0 = self.z.sqr(); v1 = self.y.sqr(); v2 = self.x.sqr()',
    '        t = (self.y + self.x).sqr() - v1 - v2',
    '        z = t.mul_u1() + v0',
    '        t = (self.z + self.y).sqr() - v0 - v1',
    '        y = t + v2.mul_u1()',
    '        t = (self.z + self.x).sqr() - v0 + v1',
    '        x = t - v2',
    '        return SM9_F6(x, y, z)',
    '    def mul_scalar(self, k): return SM9_F6(self.x.mul_scalar(k), self.y.mul_scalar(k), self.z.mul_scalar(k))',
    '    def mul_f2(self, k):',
    '        # Go gfP6.MulScalar(a, b *gfP2): multiply each F2 component by F2 k',
    '        return SM9_F6(self.x.mul(k), self.y.mul(k), self.z.mul(k))',
    '    def inv(self):',
    '        # Scott\'s method: A = z² - x·y·u ; B = x²·u - y·z ; C = y² - x·z',
    '        # F = C·y·u + A·z + B·x·u ; invF',
    '        A = self.z.sqr() - self.x.mul_u(self.y)',
    '        B = self.x.sqr_u() - self.y.mul(self.z)',
    '        C = self.y.sqr() - self.x.mul(self.z)',
    '        F = C.mul_u(self.y) + A.mul(self.z) + B.mul_u(self.x)',
    '        Fi = F.inv()',
    '        return SM9_F6(C.mul(Fi), B.mul(Fi), A.mul(Fi))',
    '    def frob(self):',
    '        # conj(z) + conj(y)·sToPMinus1·s + conj(x)·sTo2PMinus2·s²',
    '        return SM9_F6(self.x.conj().mul_scalar(SM9_S_TO_2P_MINUS_2),',
    '                  self.y.conj().mul_scalar(SM9_S_TO_P_MINUS_1),',
    '                  self.z.conj())',
    '    def frob_p2(self):',
    '        return SM9_F6(self.x.mul_scalar(SM9_S_TO_2P2_MINUS_2),',
    '                  self.y.mul_scalar(SM9_S_TO_P2_MINUS_1),',
    '                  self.z)',
    '    def frob_p4(self):',
    '        return SM9_F6(self.x.mul_scalar(SM9_S_TO_P2_MINUS_1),',
    '                  self.y.mul_scalar(SM9_S_TO_2P2_MINUS_2),',
    '                  self.z)',
    '    def is_zero(self): return self.x.is_zero() and self.y.is_zero() and self.z.is_zero()',
    '    def is_one(self): return self.x.is_zero() and self.y.is_zero() and self.z.is_one()',
    '    def __eq__(self, o): return self.x == o.x and self.y == o.y and self.z == o.z',
    '    def __repr__(self): return f\'({self.x},{self.y},{self.z})\'',
    '    @staticmethod',
    '    def one(): return SM9_F6(SM9_F2(), SM9_F2(), SM9_F2.one())',
    '    @staticmethod',
    '    def zero(): return SM9_F6(SM9_F2(), SM9_F2(), SM9_F2())',
    '',
    'class SM9_F12:',
    '    """(x, y) = x·t + y, t² = s"""',
    '    __slots__ = (\'x\', \'y\')',
    '    def __init__(self, x=None, y=None):',
    '        self.x = x if x is not None else SM9_F6()',
    '        self.y = y if y is not None else SM9_F6()',
    '    def __add__(self, o): return SM9_F12(self.x + o.x, self.y + o.y)',
    '    def __sub__(self, o): return SM9_F12(self.x - o.x, self.y - o.y)',
    '    def mul(self, o):',
    '        # (a0+a1 t)(b0+b1 t): c0 = a0b0 + a1b1·s ; c1 = (a0+a1)(b0+b1)-a0b0-a1b1',
    '        v0 = self.y.mul(o.y); v1 = self.x.mul(o.x)',
    '        tx = (self.x + self.y).mul(o.x + o.y) - v0 - v1',
    '        ty = v1.mul_s() + v0',
    '        return SM9_F12(tx, ty)',
    '    def sqr(self):',
    '        # (xt+y)² = (x²·s + y²) + 2xy·t  → F12(t-coeff=2xy, const=x²s+y²)',
    '        const = self.x.sqr().mul_s() + self.y.sqr()',
    '        tcoef = self.x.mul(self.y) + self.x.mul(self.y)',
    '        return SM9_F12(tcoef, const)',
    '    def neg(self): return SM9_F12(-self.x, -self.y)',
    '    def conj(self): return SM9_F12(-self.x, self.y)',
    '    def frob(self):',
    '        # (xt+y)^p = x^p·s^((p-1)/2)·t + y^p',
    '        return SM9_F12(self.x.frob().mul_scalar(SM9_FROB_CONST), self.y.frob())',
    '    def frob_p2(self):',
    '        return SM9_F12(self.x.frob_p2().mul_scalar(SM9_FROB_CONST), self.y.frob_p2())',
    '    def inv(self):',
    '        t0 = self.y.mul(self.y) - self.x.mul(self.x).mul_s()',
    '        t0i = t0.inv()',
    '        return SM9_F12((-self.x).mul(t0i), self.y.mul(t0i))',
    '    def pow(self, e: int):',
    '        # square-and-multiply',
    '        r = SM9_F12.one()',
    '        base = self',
    '        while e:',
    '            if e & 1:',
    '                r = r.mul(base)',
    '            base = base.sqr()',
    '            e >>= 1',
    '        return r',
    '    def is_one(self): return self.x.is_zero() and self.y.is_one()',
    '    def __eq__(self, o): return self.x == o.x and self.y == o.y',
    '    def __repr__(self): return f\'({self.x},{self.y})\'',
    '    @staticmethod',
    '    def one(): return SM9_F12(SM9_F6.zero(), SM9_F6.one())',
    '    @staticmethod',
    '    def zero(): return SM9_F12(SM9_F6.zero(), SM9_F6.zero())',
    '',
    '# ---------- G1 (E: y²=x³+5 over Fp, Jacobian) ----------',
    'class SM9_G1:',
    '    __slots__ = (\'x\', \'y\', \'z\')',
    '    def __init__(self, x=0, y=0, z=1):',
    '        self.x, self.y, self.z = x % SM9P, y % SM9P, z % SM9P',
    '    def is_inf(self): return self.z == 0',
    '    def is_on_curve(self):',
    '        if self.is_inf(): return True',
    '        # projective: Y²Z = X³ + 5·Z³',
    '        return (self.y * self.y * self.z - self.x ** 3 - 5 * self.z ** 3) % SM9P == 0',
    '    @staticmethod',
    '    def double_comp(a):',
    '        # complete doubling (a=0, b=5), Renes 2015 Alg 9',
    '        t0 = a.y * a.y % SM9P',
    '        z3 = 8 * t0 % SM9P',
    '        t1 = a.y * a.z % SM9P',
    '        t2 = a.z * a.z % SM9P',
    '        t2 = 15 * t2 % SM9P',
    '        x3 = t2 * z3 % SM9P',
    '        y3 = (t0 + t2) % SM9P',
    '        z3 = t1 * z3 % SM9P',
    '        t2 = 3 * t2 % SM9P',
    '        t0 = (t0 - t2) % SM9P',
    '        y3 = t0 * y3 % SM9P',
    '        y3 = (x3 + y3) % SM9P',
    '        t1 = a.x * a.y % SM9P',
    '        x3 = t0 * t1 % SM9P',
    '        x3 = 2 * x3 % SM9P',
    '        return SM9_G1(x3, y3, z3)',
    '    @staticmethod',
    '    def add_comp(a, b):',
    '        # complete addition (a=0, b=5), Renes 2015 Alg 7',
    '        t0 = a.x * b.x % SM9P',
    '        t1 = a.y * b.y % SM9P',
    '        t2 = a.z * b.z % SM9P',
    '        t3 = (a.x + a.y) % SM9P',
    '        t4 = (b.x + b.y) % SM9P',
    '        t3 = t3 * t4 % SM9P',
    '        t4 = (t0 + t1) % SM9P',
    '        t3 = (t3 - t4) % SM9P',
    '        t4 = (a.y + a.z) % SM9P',
    '        x3 = (b.y + b.z) % SM9P',
    '        t4 = t4 * x3 % SM9P',
    '        x3 = (t1 + t2) % SM9P',
    '        t4 = (t4 - x3) % SM9P',
    '        x3 = (a.x + a.z) % SM9P',
    '        y3 = (b.x + b.z) % SM9P',
    '        x3 = x3 * y3 % SM9P',
    '        y3 = (t0 + t2) % SM9P',
    '        y3 = (x3 - y3) % SM9P',
    '        t0 = 3 * t0 % SM9P',
    '        t2 = 15 * t2 % SM9P',
    '        z3 = (t1 + t2) % SM9P',
    '        t1 = (t1 - t2) % SM9P',
    '        y3 = 15 * y3 % SM9P',
    '        x3 = t4 * y3 % SM9P',
    '        t2 = t3 * t1 % SM9P',
    '        x3 = (t2 - x3) % SM9P',
    '        y3 = y3 * t0 % SM9P',
    '        t1 = t1 * z3 % SM9P',
    '        y3 = (t1 + y3) % SM9P',
    '        t0 = t0 * t3 % SM9P',
    '        z3 = z3 * t4 % SM9P',
    '        z3 = (z3 + t0) % SM9P',
    '        return SM9_G1(x3, y3, z3)',
    '    def add(self, o): return SM9_G1.add_comp(self, o)',
    '    def double(self): return SM9_G1.double_comp(self)',
    '    def neg(self): return SM9_G1(self.x, -self.y, self.z)',
    '    def mul(self, k: int):',
    '        r = SM9_G1(0, 1, 0)',
    '        a = SM9_G1(self.x, self.y, self.z)',
    '        k %= SM9N',
    '        while k:',
    '            if k & 1:',
    '                r = r.add(a)',
    '            a = a.double()',
    '            k >>= 1',
    '        return r',
    '    def affine(self):',
    '        if self.is_inf(): return None',
    '        zi = pow(self.z, SM9P - 2, SM9P)',
    '        return (self.x * zi % SM9P, self.y * zi % SM9P)',
    '    def marshal(self):',
    '        a = self.affine()',
    '        if a is None:',
    '            return bytes([0]) + bytes(64)',
    '        return bytes([4]) + a[0].to_bytes(32, \'big\') + a[1].to_bytes(32, \'big\')',
    '    def marshal_raw(self):',
    '        a = self.affine()',
    '        return a[0].to_bytes(32, \'big\') + a[1].to_bytes(32, \'big\')',
    '    def __eq__(self, o):',
    '        return (self.x * o.z - o.x * self.z) % SM9P == 0 and \\',
    '               (self.y * o.z - o.y * self.z) % SM9P == 0',
    '',
    'SM9_P1_G = SM9_G1(*SM9_P1)',
    '',
    '# ---------- G2 (twist y²=x³+5 over Fp2, projective with t=z²) ----------',
    'class SM9_G2:',
    '    __slots__ = (\'x\', \'y\', \'z\', \'t\')',
    '    def __init__(self, x=None, y=None, z=None, t=None):',
    '        self.x = x if x is not None else SM9_F2()',
    '        self.y = y if y is not None else SM9_F2()',
    '        self.z = z if z is not None else SM9_F2.one()',
    '        self.t = t if t is not None else SM9_F2.one()',
    '    def is_inf(self): return self.z.is_zero()',
    '    def add(self, o):',
    '        # Renes 2015 Alg 7 (b\' = 5)',
    '        t0 = self.x.mul(o.x); t1 = self.y.mul(o.y); t2 = self.z.mul(o.z)',
    '        t3 = self.x + self.y; t4 = o.x + o.y',
    '        t3 = t3.mul(t4); t4 = t0 + t1; t3 = t3 - t4',
    '        t4 = self.y + self.z; x3 = o.y + o.z',
    '        t4 = t4.mul(x3); x3 = t1 + t2; t4 = t4 - x3',
    '        x3 = self.x + self.z; y3 = o.x + o.z',
    '        x3 = x3.mul(y3); y3 = t0 + t2; y3 = x3 - y3',
    '        t0 = SM9_F2(3 * t0.x, 3 * t0.y)',
    '        t2 = SM9_F2(15, 0).mul(t2)   # 15u · Z1Z2 (F2 mul, twist b = 5u)',
    '        z3 = t1 + t2',
    '        t1 = t1 - t2',
    '        y3 = SM9_F2(15, 0).mul(y3)   # 15u · (X1Z2+X2Z1)',
    '        x3 = t4.mul(y3); t2 = t3.mul(t1); x3 = t2 - x3',
    '        y3 = y3.mul(t0); t1 = t1.mul(z3); y3 = t1 + y3',
    '        t0 = t0.mul(t3); z3 = z3.mul(t4); z3 = z3 + t0',
    '        return SM9_G2(x3, y3, z3)',
    '    def double(self):',
    '        # Renes 2015 Alg 9 (b\' = 5)',
    '        t0 = self.y.sqr()',
    '        z3 = t0 + t0; z3 = z3 + z3; z3 = z3 + z3  # 8·t0',
    '        t1 = self.y.mul(self.z)',
    '        t2 = self.z.sqr()',
    '        t2 = SM9_F2(15, 0).mul(t2)   # 3b·Z² with b = 5u',
    '        x3 = t2.mul(z3)',
    '        y3 = t0 + t2',
    '        z3 = t1.mul(z3)',
    '        t2 = SM9_F2(3 * t2.x, 3 * t2.y)',
    '        t0 = t0 - t2',
    '        y3 = t0.mul(y3)',
    '        y3 = x3 + y3',
    '        t1 = self.x.mul(self.y)',
    '        x3 = t0.mul(t1)',
    '        x3 = x3 + x3',
    '        return SM9_G2(x3, y3, z3)',
    '    def neg(self): return SM9_G2(self.x, -self.y, self.z, SM9_F2())',
    '    def mul(self, k: int):',
    '        r = SM9_G2(SM9_F2(), SM9_F2.one(), SM9_F2(), SM9_F2())',
    '        a = SM9_G2(self.x, self.y, self.z, self.t)',
    '        k %= SM9N',
    '        while k:',
    '            if k & 1:',
    '                r = r.add(a)',
    '            a = a.double()',
    '            k >>= 1',
    '        return r',
    '    def make_affine(self):',
    '        if self.z.is_one(): return',
    '        if self.z.is_zero():',
    '            self.x = SM9_F2(); self.y = SM9_F2.one(); self.z = SM9_F2(); self.t = SM9_F2()',
    '            return',
    '        zi = self.z.inv()',
    '        self.x = self.x.mul(zi)',
    '        self.y = self.y.mul(zi)',
    '        self.z = SM9_F2.one(); self.t = SM9_F2.one()',
    '    def affine(self):',
    '        g = SM9_G2(self.x, self.y, self.z, self.t)',
    '        g.make_affine()',
    '        return (g.x, g.y)',
    '    def marshal_raw(self):',
    '        x, y = self.affine()',
    '        # standard serialization: u-coeff first at each level → x0‖x1‖y0‖y1 with x = x0·u + x1',
    '        return x.x.to_bytes(32, \'big\') + x.y.to_bytes(32, \'big\') + \\',
    '               y.x.to_bytes(32, \'big\') + y.y.to_bytes(32, \'big\')',
    '    def __eq__(self, o):',
    '        self.make_affine(); o2 = SM9_G2(o.x, o.y, o.z, o.t); o2.make_affine()',
    '        return self.x == o2.x and self.y == o2.y',
    '',
    'SM9_P2_G = SM9_G2(SM9_F2(SM9_P2[0][0], SM9_P2[0][1]), SM9_F2(SM9_P2[1][0], SM9_P2[1][1]))',
    '# SM9_F2(x, y) = x·u + y; standard P2 x = 85ae..·u + 3722.. → SM9_F2(85ae.., 3722..)',
    '',
    '# ---------- line functions (bn_pair.go) ----------',
    'def sm9_line_function_add(r, p, r_out, q, r2):',
    '    # r2 = p.y² (precomputed)',
    '    B = p.x.mul(r.t)                       # B = Xp·Zr²',
    '    D = (p.y + r.z).sqr() - r2 - r.t',
    '    D = D.mul(r.t)                         # D = 2Yp·Zr³',
    '    H = B - r.x',
    '    I = H.sqr()',
    '    E = I + I; E = E + E                   # 4I',
    '    J = H.mul(E)',
    '    L1 = D - r.y - r.y                     # 2YpZr³ - 2Yr',
    '    V = r.x.mul(E)',
    '    r_out.x = L1.sqr() - J - V - V',
    '    r_out.z = (r.z + H).sqr() - r.t - I',
    '    t = (V - r_out.x).mul(L1)',
    '    t2 = r.y.mul(J); t2 = t2 + t2',
    '    r_out.y = t - t2',
    '    r_out.t = r_out.z.sqr()',
    '    t = (p.y + r_out.z).sqr() - r2 - r_out.t',
    '    t2 = L1.mul(p.x); t2 = t2 + t2',
    '    a = t2 - t',
    '    c = r_out.z.mul_scalar(q[1]); c = c + c',
    '    b = (-L1).mul_scalar(q[0]); b = b + b',
    '    return a, b, c',
    '',
    'def sm9_line_function_double(r, r_out, q):',
    '    A = r.x.sqr()',
    '    B = r.y.sqr()',
    '    C = B.sqr()',
    '    D = (r.x + B).sqr() - A - C',
    '    D = D + D',
    '    E = A + A + A                       # 3Xr²',
    '    G = E.sqr()',
    '    r_out.x = G - D - D',
    '    r_out.z = (r.y + r.z).sqr() - B - r.t',
    '    r_out.y = (D - r_out.x).mul(E) - (C + C + C + C + C + C + C + C)  # -8C',
    '    r_out.t = r_out.z.sqr()',
    '    t = E.mul(r.t); t = t + t',
    '    b = (-t).mul_scalar(q[0])',
    '    a = (r.x + E).sqr() - A - G - (B + B + B + B)',
    '    c = r_out.z.mul(r.t); c = c + c',
    '    c = c.mul_scalar(q[1])',
    '    return a, b, c',
    '',
    'def sm9_mul_line_b6(ret, a, b, c):',
    '    # ret *= (c·s)·t + (b·s + a)  — sparse mult in the t²=s tower',
    '    a2 = SM9_F6(SM9_F2(), b, a)                 # a2 = b·s + a (F6: x·s²+y·s+z → y=b,z=a)',
    '    a2 = ret.y.mul(a2)',
    '    t3 = ret.x.mul_f2(c).mul_s()',
    '    t = b + c',
    '    t2 = SM9_F6(SM9_F2(), t, a)',
    '    ret.x = ret.x + ret.y',
    '    ret.y = t3',
    '    ret.x = ret.x.mul(t2) - a2 - ret.y',
    '    ret.y = ret.y.mul_s() + a2',
    '    return ret',
    '',
    '# ---------- pairing ----------',
    'def sm9_pairing(q: SM9_G2, p: SM9_G1) -> SM9_F12:',
    '    """e(P, Q) = R-ate pairing, computed as miller(Q, P) with Q ∈ G2, P ∈ G1."""',
    '    ret = SM9_F12.one()',
    '    a_aff = SM9_G2(q.x, q.y, q.z, q.t); a_aff.make_affine()',
    '    minus_a = a_aff.neg()',
    '    b_aff = SM9_G1(p.x, p.y, p.z); b_aff = b_aff.affine()   # (x, y) tuple',
    '    r = SM9_G2(a_aff.x, a_aff.y, a_aff.z, a_aff.t)',
    '    r2 = a_aff.y.sqr()',
    '    new_r = SM9_G2()',
    '    for i in range(len(SM9_NAF_6U2) - 1, 0, -1):',
    '        a = b = c = None',
    '        a, b, c = sm9_line_function_double(r, new_r, b_aff)',
    '        if i != len(SM9_NAF_6U2) - 1:',
    '            ret = ret.sqr()',
    '        ret = sm9_mul_line_b6(ret, a, b, c)',
    '        r, new_r = new_r, r',
    '        d = SM9_NAF_6U2[i - 1]',
    '        if d == 1:',
    '            a, b, c = sm9_line_function_add(r, a_aff, new_r, b_aff, r2)',
    '        elif d == -1:',
    '            a, b, c = sm9_line_function_add(r, minus_a, new_r, b_aff, r2)',
    '        else:',
    '            continue',
    '        ret = sm9_mul_line_b6(ret, a, b, c)',
    '        r, new_r = new_r, r',
    '    # Q1 = [p]Q, minusQ2 = -[p²]Q',
    '    q1 = SM9_G2()',
    '    q1.x = a_aff.x.conj().mul_scalar(SM9_BETA_NEG_PP1_O3)',
    '    q1.y = a_aff.y.conj().mul_scalar(SM9_BETA_NEG_PP1_O2)',
    '    q1.z = SM9_F2.one(); q1.t = SM9_F2.one()',
    '    mq2 = SM9_G2()',
    '    mq2.x = a_aff.x.mul_scalar(SM9_BETA_NEG_P2P1_O3)',
    '    mq2.y = (-a_aff.y).mul_scalar(SM9_BETA_NEG_P2P1_O2)',
    '    mq2.z = SM9_F2.one(); mq2.t = SM9_F2.one()',
    '    r2 = q1.y.sqr()',
    '    a, b, c = sm9_line_function_add(r, q1, new_r, b_aff, r2)',
    '    ret = sm9_mul_line_b6(ret, a, b, c)',
    '    r, new_r = new_r, r',
    '    r2 = mq2.y.sqr()',
    '    a, b, c = sm9_line_function_add(r, mq2, new_r, b_aff, r2)',
    '    ret = sm9_mul_line_b6(ret, a, b, c)',
    '    # final exponentiation: f^{(p^12-1)/r}',
    '    return ret.pow((SM9P ** 12 - 1) // SM9N)',
    '',
    '# ---------- SM9 signature scheme ----------',
    'def sm9_keygen(ks: int, uid: bytes, hid: int):',
    '    """Returns (ds: G1, Ppub: G2, g: F12)."""',
    '    t1 = sm9_H1(uid + bytes([hid]))',
    '    t1 = (t1 + ks) % SM9N',
    '    if t1 == 0:',
    '        raise ValueError(\'bad master key\')',
    '    t2 = ks * pow(t1, SM9N - 2, SM9N) % SM9N',
    '    ds = SM9_P1_G.mul(t2)',
    '    ppub = SM9_P2_G.mul(ks)',
    '    g = sm9_pairing(ppub, SM9_P1_G)  # e(P1, Ppub)',
    '    return ds, ppub, g',
    '',
    'def sm9_sign_impl(msg: bytes, ds: SM9_G1, ppub: SM9_G2, r: int) -> tuple:',
    '    g = sm9_pairing(ppub, SM9_P1_G)',
    '    w = g.pow(r)',
    '    h = sm9_H2(msg + sm9_gt_marshal(w))',
    '    l = (r - h) % SM9N',
    '    S = ds.mul(l)',
    '    return h, S',
    '',
    'def sm9_verify_impl(msg: bytes, uid: bytes, hid: int, ppub: SM9_G2, h: int, S: SM9_G1) -> bool:',
    '    if h <= 0 or h >= SM9N:',
    '        return False',
    '    if not S.is_on_curve() or S.is_inf():',
    '        return False',
    '    t1 = sm9_H1(uid + bytes([hid]))',
    '    Q = SM9_P2_G.mul(t1).add(ppub)',
    '    g = sm9_pairing(ppub, SM9_P1_G)',
    '    u = sm9_pairing(Q, S)          # e(S, Q)',
    '    w = u.mul(g.pow(h))',
    '    h2 = sm9_H2(msg + sm9_gt_marshal(w))',
    '    return h2 == h',
    '',
    'def sm9_gt_marshal(f: SM9_F12) -> bytes:',
    '    """384-byte GT serialization — standard order (uv·w², v·w², u·w², w², uv·w, v·w, u·w, w, uv, v, u, 1).',
    '    In the b6 tower (t=w): t⁵u, t⁵, t²u, t², t⁴u, t⁴, tu, t, t³u, t³, u, 1."""',
    '    out = b\'\'',
    '    for coeff in (f.x.x, f.y.y, f.y.x, f.x.z, f.x.y, f.y.z):',
    '        out += coeff.x.to_bytes(32, \'big\') + coeff.y.to_bytes(32, \'big\')',
    '    return out',
    '',
    '# ---------- G1/G2 parse helpers (raw 64B / 128B, u-coeff first at each level) ----------',
    'def sm9_g1_parse_raw(b):',
    '    x = int.from_bytes(bytes(b[:32]), \'big\')',
    '    y = int.from_bytes(bytes(b[32:64]), \'big\')',
    '    return SM9_G1(x, y, 1)',
    '',
    'def sm9_g2_parse_raw(b):',
    '    c = [int.from_bytes(bytes(b[k*32:(k+1)*32]), \'big\') for k in range(4)]',
    '    return SM9_G2(SM9_F2(c[0], c[1]), SM9_F2(c[2], c[3]), SM9_F2.one(), SM9_F2.one())',
    '',
    '# ---------- block entry points (BYTES in/out, list of ints) ----------',
    'def sm9_master_key(ks):',
    '    ks_bytes = bytes(ks)',
    '    if len(ks_bytes) != 32:',
    '        raise ValueError(\'SM9 master key must be 32 bytes\')',
    '    k = int.from_bytes(ks_bytes, \'big\')',
    '    ppub = SM9_P2_G.mul(k)',
    '    return list(ppub.marshal_raw())',
    '',
    'def sm9_user_key(ks, uid, hid):',
    '    ks_bytes = bytes(ks)',
    '    if len(ks_bytes) != 32:',
    '        raise ValueError(\'SM9 master key must be 32 bytes\')',
    '    k = int.from_bytes(ks_bytes, \'big\')',
    '    ds, ppub, g = sm9_keygen(k, bytes(uid), int(hid))',
    '    return list(ds.marshal_raw())',
    '',
    'def ' + pythonGenerator.FUNCTION_NAME_PLACEHOLDER_ + '(msg, ds, ppub, r):',
    '    ds_b = bytes(ds)',
    '    ppub_b = bytes(ppub)',
    '    if len(ds_b) != 64:',
    '        raise ValueError(\'SM9 ds must be 64 bytes\')',
    '    if len(ppub_b) != 128:',
    '        raise ValueError(\'SM9 Ppub must be 128 bytes\')',
    '    if not r:',
    '        import os',
    '        r = list(os.urandom(32))',
    '    if len(r) != 32:',
    '        raise ValueError(\'SM9 r must be 32 bytes or empty\')',
    '    r_int = int.from_bytes(bytes(r), \'big\')',
    '    h, S = sm9_sign_impl(bytes(msg), sm9_g1_parse_raw(ds_b), sm9_g2_parse_raw(ppub_b), r_int)',
    '    return list(h.to_bytes(32, \'big\')) + list(S.marshal())',
    '',
    'def sm9_verify(msg, uid, h, s, ppub, hid):',
    '    h_b = bytes(h)',
    '    s_b = bytes(s)',
    '    ppub_b = bytes(ppub)',
    '    if len(h_b) != 32:',
    '        return False',
    '    if len(s_b) != 65 or s_b[0] != 4:',
    '        return False',
    '    if len(ppub_b) != 128:',
    '        return False',
    '    h_int = int.from_bytes(h_b, \'big\')',
    '    S_g1 = sm9_g1_parse_raw(s_b[1:])',
    '    ppub_g2 = sm9_g2_parse_raw(ppub_b)',
    '    return sm9_verify_impl(bytes(msg), bytes(uid), int(hid), ppub_g2, h_int, S_g1)',
    '',
  ]);
}

pythonGenerator.forBlock['sm9_master_key'] = function (block: Block): [string, number] {
  const ks = pythonGenerator.valueToCode(block, 'KS', Order.ATOMIC) || '[]';
  registerSm9();
  return ['sm9_master_key(' + ks + ')', Order.ATOMIC];
};

pythonGenerator.forBlock['sm9_user_key'] = function (block: Block): [string, number] {
  const ks = pythonGenerator.valueToCode(block, 'KS', Order.ATOMIC) || '[]';
  const id = pythonGenerator.valueToCode(block, 'ID', Order.ATOMIC) || '[]';
  const hid = block.getFieldValue('HID') || '1';
  registerSm9();
  return ['sm9_user_key(' + ks + ', ' + id + ', ' + hid + ')', Order.ATOMIC];
};

pythonGenerator.forBlock['sm9_sign'] = function (block: Block): [string, number] {
  const msg = pythonGenerator.valueToCode(block, 'MSG', Order.ATOMIC) || '[]';
  const ds = pythonGenerator.valueToCode(block, 'DS', Order.ATOMIC) || '[]';
  const ppub = pythonGenerator.valueToCode(block, 'PPUB', Order.ATOMIC) || '[]';
  const r = pythonGenerator.valueToCode(block, 'R', Order.ATOMIC) || '[]';
  registerSm9();
  return ['sm9_sign(' + msg + ', ' + ds + ', ' + ppub + ', ' + r + ')', Order.ATOMIC];
};

pythonGenerator.forBlock['sm9_verify'] = function (block: Block): [string, number] {
  const msg = pythonGenerator.valueToCode(block, 'MSG', Order.ATOMIC) || '[]';
  const id = pythonGenerator.valueToCode(block, 'ID', Order.ATOMIC) || '[]';
  const h = pythonGenerator.valueToCode(block, 'H', Order.ATOMIC) || '[]';
  const s = pythonGenerator.valueToCode(block, 'S', Order.ATOMIC) || '[]';
  const ppub = pythonGenerator.valueToCode(block, 'PPUB', Order.ATOMIC) || '[]';
  const hid = block.getFieldValue('HID') || '1';
  registerSm9();
  return ['sm9_verify(' + msg + ', ' + id + ', ' + h + ', ' + s + ', ' + ppub + ', ' + hid + ')', Order.ATOMIC];
};

