/**
 * Goppa 码 Patterson 译码 JavaScript 生成器（McEliece 基于纠错码方案，完整算法闭包）
 *
 * 闭包 goppaCore：GF(2^8) AES 域（0x11B）+ 多项式环运算 + 16×16 Frobenius 开方。
 * 与 Python 生成器逐行镜像（σ = r² + z·B²）。
 */
import { javascriptGenerator, Order } from 'blockly/javascript';
import type { Block } from 'blockly/core';

function registerGoppaCore(): string {
  return javascriptGenerator.provideFunction_('goppaCore', [
    'function ' + javascriptGenerator.FUNCTION_NAME_PLACEHOLDER_ + '() {',
    '  function trim(p) {',
    '    p = p.slice();',
    '    while (p.length > 1 && p[p.length - 1] === 0) p.pop();',
    '    return p;',
    '  }',
    '  function gfMul(a, b) {',
    '    let p = 0;',
    '    for (let i = 0; i < 8; i++) {',
    '      if (b & 1) p ^= a;',
    '      let hi = a & 0x80;',
    '      a = (a << 1) & 0xFF;',
    '      if (hi) a ^= 0x1B;',
    '      b >>= 1;',
    '    }',
    '    return p;',
    '  }',
    '  function gfInv(a) {',
    '    if (a === 0) return 0;',
    '    let r = 1;',
    '    for (let bit of (254).toString(2)) {',
    '      r = gfMul(r, r);',
    '      if (bit === "1") r = gfMul(r, a);',
    '    }',
    '    return r;',
    '  }',
    '  function polyAdd(a, b) {',
    '    let out = new Array(Math.max(a.length, b.length)).fill(0);',
    '    for (let i = 0; i < a.length; i++) out[i] ^= a[i];',
    '    for (let i = 0; i < b.length; i++) out[i] ^= b[i];',
    '    return trim(out);',
    '  }',
    '  function polyMul(a, b) {',
    '    let out = new Array(a.length + b.length - 1).fill(0);',
    '    for (let i = 0; i < a.length; i++) {',
    '      if (!a[i]) continue;',
    '      for (let j = 0; j < b.length; j++) {',
    '        if (b[j]) out[i + j] ^= gfMul(a[i], b[j]);',
    '      }',
    '    }',
    '    return trim(out);',
    '  }',
    '  function polyDivmod(a, b) {',
    '    a = trim(a); b = trim(b);',
    '    if (b.length === 1 && b[0] === 0) return [[0], [0]];',
    '    let lcInv = gfInv(b[b.length - 1]);',
    '    let q = new Array(Math.max(a.length - b.length + 1, 0)).fill(0);',
    '    let r = a.slice();',
    '    while (r.length >= b.length) {',
    '      let qc = gfMul(r[r.length - 1], lcInv);',
    '      if (qc) {',
    '        let shift = r.length - b.length;',
    '        q[shift] = qc;',
    '        for (let i = 0; i < b.length; i++) r[shift + i] ^= gfMul(qc, b[i]);',
    '      }',
    '      r.pop();',
    '    }',
    '    return [trim(q), trim(r.length ? r : [0])];',
    '  }',
    '  function polyMod(a, b) { return polyDivmod(a, b)[1]; }',
    '  function polyXgcd(a, b) {',
    '    let r0 = trim(a), r1 = trim(b);',
    '    let s0 = [1], s1 = [0];',
    '    let t0 = [0], t1 = [1];',
    '    while (!(r1.length === 1 && r1[0] === 0)) {',
    '      let dm = polyDivmod(r0, r1);',
    '      let q = dm[0], r = dm[1];',
    '      r0 = r1; r1 = r;',
    '      let ns = polyAdd(s0, polyMul(q, s1)); s0 = s1; s1 = ns;',
    '      let nt = polyAdd(t0, polyMul(q, t1)); t0 = t1; t1 = nt;',
    '    }',
    '    let lc = r0[r0.length - 1];',
    '    if (lc !== 1) {',
    '      let inv = gfInv(lc);',
    '      r0 = r0.map((c) => gfMul(c, inv));',
    '      s0 = s0.map((c) => gfMul(c, inv));',
    '      t0 = t0.map((c) => gfMul(c, inv));',
    '    }',
    '    return [s0.length].concat(s0, [t0.length], t0, r0);',
    '  }',
    '  function polyEval(p, x) {',
    '    let r = 0;',
    '    p = trim(p);',
    '    for (let i = p.length - 1; i >= 0; i--) r = gfMul(r, x) ^ p[i];',
    '    return r;',
    '  }',
    '  function ringSqrtMod(u, g) {',
    '    let t = trim(g).length - 1;',
    '    let n = t * 8;',
    '    let cols = [];',
    '    for (let i = 0; i < t; i++) {',
    '      for (let j = 0; j < 8; j++) {',
    '        let e = new Array(t).fill(0);',
    '        e[i] = 1 << j;',
    '        let sq = polyMod(polyMul(e, e), g);',
    '        while (sq.length < t) sq.push(0);',
    '        let col = [];',
    '        for (let ii = 0; ii < t; ii++) {',
    '          let c = sq[ii];',
    '          for (let jj = 0; jj < 8; jj++) col.push((c >> jj) & 1);',
    '        }',
    '        cols.push(col);',
    '      }',
    '    }',
    '    let m = [];',
    '    for (let k = 0; k < n; k++) {',
    '      let row = [];',
    '      for (let l = 0; l < n; l++) row.push(cols[l][k]);',
    '      m.push(row);',
    '    }',
    '    let uu = polyMod(u, g);',
    '    while (uu.length < t) uu.push(0);',
    '    let b = [];',
    '    for (let ii = 0; ii < t; ii++) {',
    '      let c = uu[ii];',
    '      for (let jj = 0; jj < 8; jj++) b.push((c >> jj) & 1);',
    '    }',
    '    let aug = m.map((row, i) => row.slice().concat([b[i]]));',
    '    for (let col = 0; col < n; col++) {',
    '      let piv = -1;',
    '      for (let r = col; r < n; r++) {',
    '        if (aug[r][col]) { piv = r; break; }',
    '      }',
    '      if (piv < 0) return [0];',
    '      if (piv !== col) { let tmp = aug[col]; aug[col] = aug[piv]; aug[piv] = tmp; }',
    '      for (let r2 = 0; r2 < n; r2++) {',
    '        if (r2 !== col && aug[r2][col]) {',
    '          for (let j2 = 0; j2 <= n; j2++) aug[r2][j2] ^= aug[col][j2];',
    '        }',
    '      }',
    '    }',
    '    let out = new Array(t).fill(0);',
    '    for (let ii = 0; ii < t; ii++) {',
    '      for (let jj = 0; jj < 8; jj++) out[ii] |= (aug[ii * 8 + jj][n] << jj);',
    '    }',
    '    return trim(out);',
    '  }',
    '  function goppaDecode(y, g, L) {',
    '    y = y.map((v) => v & 1);',
    '    g = trim(g); L = Array.from(L);',
    '    let t = g.length - 1;',
    '    let S = [0];',
    '    for (let i = 0; i < y.length; i++) {',
    '      if (y[i]) {',
    '        let p = polyXgcd(polyMod([L[i], 1], g), g);',
    '        let lu = p[0];',
    '        S = polyAdd(S, p.slice(1, 1 + lu));',
    '      }',
    '    }',
    '    S = polyMod(S, g);',
    '    if (trim(S).length === 1 && trim(S)[0] === 0) return y;',
    '    let p = polyXgcd(S, g);',
    '    let sinv = p.slice(1, 1 + p[0]);',
    '    let T = ringSqrtMod(polyAdd([0, 1], sinv), g);',
    '    let bound = (t / 2) | 0;',
    '    let r0 = g, r1 = T;',
    '    let s0 = [1], s1 = [0];',
    '    let u0 = [0], u1 = [1];',
    '    while (trim(r1).length - 1 > bound) {',
    '      let dm = polyDivmod(r0, r1);',
    '      let q = dm[0], r = dm[1];',
    '      r0 = r1; r1 = r;',
    '      let ns = polyAdd(s0, polyMul(q, s1)); s0 = s1; s1 = ns;',
    '      let nt = polyAdd(u0, polyMul(q, u1)); u0 = u1; u1 = nt;',
    '    }',
    '    let sigma = polyAdd(polyMul(r1, r1), polyMul([0, 1], polyMul(u1, u1)));',
    '    let out = y.slice();',
    '    for (let i = 0; i < L.length; i++) {',
    '      if (polyEval(sigma, L[i]) === 0) out[i] ^= 1;',
    '    }',
    '    return out;',
    '  }',
    '  return { goppaDecode: goppaDecode };',
    '}',
  ]);
}

javascriptGenerator.forBlock['goppa_decode'] = function (block: Block): [string, number] {
  const y = javascriptGenerator.valueToCode(block, 'Y', Order.ATOMIC) || '[]';
  const g = javascriptGenerator.valueToCode(block, 'G', Order.ATOMIC) || '[]';
  const L = javascriptGenerator.valueToCode(block, 'L', Order.ATOMIC) || '[]';
  const fn = registerGoppaCore();
  return [fn + '().goppaDecode(' + y + ', ' + g + ', ' + L + ')', Order.ATOMIC];
};
