/**
 * ML-DSA-44 原子块 JavaScript 代码生成器
 * FIPS 204 final
 *
 * 内嵌完整 ML-DSA-44（单 mlDsaCore() 闭包，内部所有辅助函数逐行取自已验证算法
 * mldsa_js_algo.js；常量在闭包顶部声明一次，避免 per-function var 内联时
 * 一行函数 return 先于常量赋值执行导致 undefined 的死循环坑）。
 * - SHAKE128/256（rate 168/136）自实现 Keccak-f1600（BigInt 64 位字）
 * - NTT/INTT（ζ = 1753, F = 8347681）、mask 采样 γ1=2^17、hint 打包 ω=80
 * - mlDsaSign 确定性：rnd 缺省 = 0^32，ctx 缺省 = []（空上下文外部接口）
 * 官方向量：NIST ACVP sigGen ML-DSA-44 deterministic 30/30 PASS（external+internal）。
 */
import { javascriptGenerator, Order } from 'blockly/javascript';
import type { Block } from 'blockly/core';

/** ML-DSA-44 完整实现（闭包：常量 + 全部辅助函数 + 入口，返回对象） */
function registerMlDsaCore(): string {
  return javascriptGenerator.provideFunction_('mlDsaCore', [
    'function ' + javascriptGenerator.FUNCTION_NAME_PLACEHOLDER_ + '() {',
    '  var Q=8380417,N=256,D=13,TAU=39,GAMMA1=131072,GAMMA2=95232,K=4,L=4,ETA=2,BETA=78,OMEGA=80,CTILDE_LEN=32,ZETA=1753,F_INTT=8347681,MVAL=44,Q_HALF=4190208;',
    '  function mlDsaMod(x) {',
    '    x = x % Q;',
    '    if (x < 0) x += Q;',
    '    return x;',
    '  }',
    '  function mlDsaCentered(x) {',
    '    x = mlDsaMod(x);',
    '    if (x > Q_HALF) x -= Q;',
    '    return x;',
    '  }',
    '  function mlDsaBitRev8(x) {',
    '    var r = 0;',
    '    for (var i = 0; i < 8; i++) {',
    '      r = (r << 1) | (x & 1);',
    '      x >>= 1;',
    '    }',
    '    return r;',
    '  }',
    '  function mlDsaModPow(a, e, m) {',
    '    var r = 1 % m;',
    '    a = a % m;',
    '    while (e > 0) {',
    '      if (e & 1) r = (r * a) % m;',
    '      a = (a * a) % m;',
    '      e >>= 1;',
    '    }',
    '    return r;',
    '  }',
    '  function mlDsaKeccakF1600(state) {',
    '    var RC = [',
    '      0x0000000000000001n, 0x0000000000008082n, 0x800000000000808An, 0x8000000080008000n,',
    '      0x000000000000808Bn, 0x0000000080000001n, 0x8000000080008081n, 0x8000000000008009n,',
    '      0x000000000000008An, 0x0000000000000088n, 0x0000000080008009n, 0x000000008000000An,',
    '      0x000000008000808Bn, 0x800000000000008Bn, 0x8000000000008089n, 0x8000000000008003n,',
    '      0x8000000000008002n, 0x8000000000000080n, 0x000000000000800An, 0x800000008000000An,',
    '      0x8000000080008081n, 0x8000000000008080n, 0x0000000080000001n, 0x8000000080008008n,',
    '    ];',
    '    var R = [[0, 36, 3, 41, 18], [1, 44, 10, 45, 2], [62, 6, 43, 15, 61], [28, 55, 25, 21, 56], [27, 20, 39, 8, 14]];',
    '    var M = 0xFFFFFFFFFFFFFFFFn;',
    '    var s = state.slice();',
    '    for (var round = 0; round < 24; round++) {',
    '      var C = new Array(5), Dd = new Array(5);',
    '      for (var x = 0; x < 5; x++) C[x] = s[x] ^ s[x + 5] ^ s[x + 10] ^ s[x + 15] ^ s[x + 20];',
    '      for (var x = 0; x < 5; x++) Dd[x] = C[(x + 4) % 5] ^ ((C[(x + 1) % 5] << 1n) | (C[(x + 1) % 5] >> 63n)) & M;',
    '      for (var i = 0; i < 25; i++) s[i] ^= Dd[i % 5];',
    '      var B = new Array(25);',
    '      for (var x = 0; x < 5; x++) {',
    '        for (var y = 0; y < 5; y++) {',
    '          var r = R[x][y];',
    '          B[((2 * x + 3 * y) % 5) * 5 + y] = ((s[x + y * 5] << BigInt(r)) | (s[x + y * 5] >> BigInt(64 - r))) & M;',
    '        }',
    '      }',
    '      for (var x = 0; x < 5; x++) {',
    '        for (var y = 0; y < 5; y++) {',
    '          s[x + y * 5] = B[x + y * 5] ^ ((~B[(x + 1) % 5 + y * 5]) & B[(x + 2) % 5 + y * 5]);',
    '        }',
    '      }',
    '      s[0] ^= RC[round];',
    '    }',
    '    return s;',
    '  }',
    '  function mlDsaShake(inp, outLen, rate) {',
    '    if (inp instanceof Uint8Array) inp = Array.from(inp);',
    '    var state = new Array(25).fill(0n);',
    '    var padLen = rate - (inp.length % rate);',
    '    if (padLen === 1) padLen += rate;',
    '    var padded = new Uint8Array(inp.length + padLen);',
    '    padded.set(inp);',
    '    padded[inp.length] = 0x1F;',
    '    padded[padded.length - 1] ^= 0x80;',
    '    var absorb = 0;',
    '    while (absorb < padded.length) {',
    '      for (var j = 0; j < rate; j += 8) {',
    '        var w = 0n;',
    '        for (var b = 0; b < 8 && (absorb + j + b) < padded.length; b++) {',
    '          w |= BigInt(padded[absorb + j + b]) << BigInt(8 * b);',
    '        }',
    '        state[j / 8] ^= w;',
    '      }',
    '      state = mlDsaKeccakF1600(state);',
    '      absorb += rate;',
    '    }',
    '    var out = [];',
    '    var cursor = 0;',
    '    while (cursor < outLen) {',
    '      for (var j = 0; j < rate && cursor < outLen; j += 8) {',
    '        var w = state[j / 8];',
    '        for (var b = 0; b < 8 && cursor < outLen; b++) {',
    '          out.push(Number((w >> BigInt(8 * b)) & 0xFFn));',
    '          cursor++;',
    '        }',
    '      }',
    '      if (cursor < outLen) state = mlDsaKeccakF1600(state);',
    '    }',
    '    return out;',
    '  }',
    '  function mlDsaZetas() {',
    '    var z = new Array(256).fill(0);',
    '    for (var k = 1; k < 256; k++) z[k] = mlDsaModPow(ZETA, mlDsaBitRev8(k), Q);',
    '    return z;',
    '  }',
    '  function mlDsaNtt(a) {',
    '    a = a.slice();',
    '    var m = 0;',
    '    var length = 128;',
    '    while (length >= 1) {',
    '      var start = 0;',
    '      while (start < 256) {',
    '        m += 1;',
    '        var z = ZETAS[m];',
    '        for (var j = start; j < start + length; j++) {',
    '          var t = (z * a[j + length]) % Q;',
    '          a[j + length] = mlDsaMod(a[j] - t);',
    '          a[j] = mlDsaMod(a[j] + t);',
    '        }',
    '        start += 2 * length;',
    '      }',
    '      length = Math.floor(length / 2);',
    '    }',
    '    return a;',
    '  }',
    '  function mlDsaIntt(a) {',
    '    a = a.slice();',
    '    var m = 256;',
    '    var length = 1;',
    '    while (length < 256) {',
    '      var start = 0;',
    '      while (start < 256) {',
    '        m -= 1;',
    '        var z = Q - ZETAS[m]; // -zetas[m] mod q',
    '        for (var j = start; j < start + length; j++) {',
    '          var t = a[j];',
    '          a[j] = mlDsaMod(t + a[j + length]);',
    '          a[j + length] = mlDsaMod(t - a[j + length]);',
    '          a[j + length] = (z * a[j + length]) % Q;',
    '        }',
    '        start += 2 * length;',
    '      }',
    '      length *= 2;',
    '    }',
    '    for (var j = 0; j < 256; j++) a[j] = (F_INTT * a[j]) % Q;',
    '    return a;',
    '  }',
    '  function mlDsaMulNtt(ai, bi) {',
    '    var c = new Array(256);',
    '    for (var i = 0; i < 256; i++) c[i] = (ai[i] * bi[i]) % Q;',
    '    return c;',
    '  }',
    '  function mlDsaDecompose(r) {',
    '    var rp = mlDsaMod(r);',
    '    var r0 = rp % (2 * GAMMA2);',
    '    if (r0 > GAMMA2) r0 -= 2 * GAMMA2;',
    '    if (rp - r0 === Q - 1) return [0, r0 - 1];',
    '    return [Math.floor((rp - r0) / (2 * GAMMA2)), r0];',
    '  }',
    '  function mlDsaHighBits(r) { return mlDsaDecompose(r)[0]; }',
    '  function mlDsaLowBits(r) { return mlDsaDecompose(r)[1]; }',
    '  function mlDsaPower2Round(r) {',
    '    var rp = mlDsaMod(r);',
    '    var r0 = rp % (1 << D);',
    '    if (r0 > (1 << (D - 1))) r0 -= (1 << D);',
    '    return [Math.floor((rp - r0) / (1 << D)), r0];',
    '  }',
    '  function mlDsaMakeHint(z, r) {',
    '    return mlDsaHighBits(r) === mlDsaHighBits(mlDsaMod(r + z)) ? 0 : 1;',
    '  }',
    '  function mlDsaUseHint(h, r) {',
    '    var dec = mlDsaDecompose(r);',
    '    var r1 = dec[0], r0 = dec[1];',
    '    if (h === 1 && r0 > 0) return (r1 + 1) % MVAL;',
    '    if (h === 1 && r0 <= 0) return (r1 - 1 + MVAL) % MVAL;',
    '    return r1;',
    '  }',
    '  function mlDsaSampleInBall(seed) {',
    '    var h = mlDsaShake(seed, 64, 136);',
    '    var c = new Array(256).fill(0);',
    '    var buflen = 64;',
    '    var buf = mlDsaShake(seed, buflen, 136);',
    '    var idx = 8;',
    '    for (var i = 256 - TAU; i < 256; i++) {',
    '      var j = buf[idx];',
    '      idx += 1;',
    '      while (j > i) {',
    '        if (idx >= buflen) { buflen *= 2; buf = mlDsaShake(seed, buflen, 136); }',
    '        j = buf[idx];',
    '        idx += 1;',
    '      }',
    '      c[i] = c[j];',
    '      // sign bit k = h[k>>3] bit (k&7); avoid 32-bit shift wrap on 64-bit sign word',
    '      var k = i + TAU - 256;',
    '      c[j] = ((h[k >> 3] >> (k & 7)) & 1) === 1 ? -1 : 1;',
    '    }',
    '    return c;',
    '  }',
    '  function mlDsaRejNttPoly(seed) {',
    '    var a = [];',
    '    var buflen = 136;',
    '    var buf = mlDsaShake(seed, buflen, 168); // SHAKE128',
    '    var idx = 0;',
    '    while (a.length < 256) {',
    '      if (idx + 3 > buflen) { buflen *= 2; buf = mlDsaShake(seed, buflen, 168); }',
    '      var b0 = buf[idx], b1 = buf[idx + 1], b2 = buf[idx + 2];',
    '      idx += 3;',
    '      var z = b0 | (b1 << 8) | ((b2 & 0x7F) << 16);',
    '      if (z < Q) a.push(z);',
    '    }',
    '    return a;',
    '  }',
    '  function mlDsaRejBoundedPoly(seed) {',
    '    var a = [];',
    '    var buflen = 136;',
    '    var buf = mlDsaShake(seed, buflen, 136); // SHAKE256',
    '    var idx = 0;',
    '    while (a.length < 256) {',
    '      if (idx >= buflen) { buflen *= 2; buf = mlDsaShake(seed, buflen, 136); }',
    '      var z = buf[idx];',
    '      idx += 1;',
    '      var n0 = z & 0x0F;',
    '      var n1 = z >> 4;',
    '      if (n0 < 15) a.push(2 - (n0 % 5));',
    '      if (n1 < 15 && a.length < 256) a.push(2 - (n1 % 5));',
    '    }',
    '    return a;',
    '  }',
    '  function mlDsaExpandA(rho) {',
    '    var A = [];',
    '    for (var r = 0; r < K; r++) {',
    '      var row = [];',
    '      for (var s = 0; s < L; s++) row.push(mlDsaRejNttPoly(rho.concat([s, r])));',
    '      A.push(row);',
    '    }',
    '    return A;',
    '  }',
    '  function mlDsaExpandMask(rhop2, mu) {',
    '    var y = [];',
    '    for (var r = 0; r < L; r++) {',
    '      var nonce = mu + r;',
    '      var seed = rhop2.concat([nonce & 0xFF, Math.floor(nonce / 256) & 0xFF]);',
    '      var v = mlDsaShake(seed, 576, 136);',
    '      var poly = [];',
    '      for (var j = 0; j < 256; j++) {',
    '        var pos = 18 * j;',
    '        var bo = Math.floor(pos / 8);',
    '        var sh = pos & 7;',
    '        var t = (v[bo] | (v[bo + 1] << 8) | (v[bo + 2] << 16)) >> sh;',
    '        t &= 0x3FFFF;',
    '        poly.push(GAMMA1 - t);',
    '      }',
    '      y.push(poly);',
    '    }',
    '    return y;',
    '  }',
    '  function mlDsaPackBits(poly, bits, outLen, offset) {',
    '    var out = new Array(outLen).fill(0);',
    '    for (var j = 0; j < 256; j++) {',
    '      var v = offset - poly[j];',
    '      for (var b = 0; b < bits; b++) {',
    '        var p = bits * j + b;',
    '        out[p >> 3] |= ((v >> b) & 1) << (p & 7);',
    '      }',
    '    }',
    '    return out;',
    '  }',
    '  function mlDsaUnpackBits(v, bits, offset) {',
    '    var poly = new Array(256);',
    '    for (var j = 0; j < 256; j++) {',
    '      var t = 0;',
    '      for (var b = 0; b < bits; b++) {',
    '        var p = bits * j + b;',
    '        t |= ((v[p >> 3] >> (p & 7)) & 1) << b;',
    '      }',
    '      poly[j] = offset - t;',
    '    }',
    '    return poly;',
    '  }',
    '  function mlDsaPack18(zp) { return mlDsaPackBits(zp, 18, 576, GAMMA1); }',
    '  function mlDsaUnpack18(v) { return mlDsaUnpackBits(v, 18, GAMMA1); }',
    '  function mlDsaPack3(sp) { return mlDsaPackBits(sp, 3, 96, ETA); }',
    '  function mlDsaUnpack3(v) { return mlDsaUnpackBits(v, 3, ETA); }',
    '  function mlDsaPack13(t0p) { return mlDsaPackBits(t0p, 13, 416, 1 << (D - 1)); }',
    '  function mlDsaUnpack13(v) { return mlDsaUnpackBits(v, 13, 1 << (D - 1)); }',
    '  function mlDsaPack10Raw(poly) {',
    '    var out = new Array(320).fill(0);',
    '    for (var j = 0; j < 256; j++) {',
    '      var v = poly[j];',
    '      for (var b = 0; b < 10; b++) {',
    '        var p = 10 * j + b;',
    '        out[p >> 3] |= ((v >> b) & 1) << (p & 7);',
    '      }',
    '    }',
    '    return out;',
    '  }',
    '  function mlDsaUnpack10Raw(v) {',
    '    var poly = new Array(256);',
    '    for (var j = 0; j < 256; j++) {',
    '      var t = 0;',
    '      for (var b = 0; b < 10; b++) {',
    '        var p = 10 * j + b;',
    '        t |= ((v[p >> 3] >> (p & 7)) & 1) << b;',
    '      }',
    '      poly[j] = t;',
    '    }',
    '    return poly;',
    '  }',
    '  function mlDsaPack6Raw(poly) {',
    '    var out = new Array(192).fill(0);',
    '    for (var j = 0; j < 256; j++) {',
    '      var v = poly[j];',
    '      for (var b = 0; b < 6; b++) {',
    '        var p = 6 * j + b;',
    '        out[p >> 3] |= ((v >> b) & 1) << (p & 7);',
    '      }',
    '    }',
    '    return out;',
    '  }',
    '  function mlDsaUnpack6Raw(v) {',
    '    var poly = new Array(256);',
    '    for (var j = 0; j < 256; j++) {',
    '      var t = 0;',
    '      for (var b = 0; b < 6; b++) {',
    '        var p = 6 * j + b;',
    '        t |= ((v[p >> 3] >> (p & 7)) & 1) << b;',
    '      }',
    '      poly[j] = t;',
    '    }',
    '    return poly;',
    '  }',
    '  function mlDsaHintPack(h) {',
    '    var y = new Array(OMEGA + K).fill(0);',
    '    var idx = 0;',
    '    for (var i = 0; i < K; i++) {',
    '      for (var j = 0; j < 256; j++) {',
    '        if (h[i][j]) { y[idx] = j; idx += 1; }',
    '      }',
    '      y[OMEGA + i] = idx;',
    '    }',
    '    return y;',
    '  }',
    '  function mlDsaHintUnpack(y) {',
    '    var h = [];',
    '    for (var i = 0; i < K; i++) h.push(new Array(256).fill(0));',
    '    var idx = 0;',
    '    for (var i = 0; i < K; i++) {',
    '      if (y[OMEGA + i] < idx || y[OMEGA + i] > OMEGA) return null;',
    '      var first = idx;',
    '      while (idx < y[OMEGA + i]) {',
    '        if (idx > first && y[idx - 1] >= y[idx]) return null;',
    '        h[i][y[idx]] = 1;',
    '        idx += 1;',
    '      }',
    '    }',
    '    for (var i = idx; i < OMEGA; i++) {',
    '      if (y[i] !== 0) return null;',
    '    }',
    '    return h;',
    '  }',
    '  function mlDsaSkDecode(sk) {',
    '    var rho = sk.slice(0, 32);',
    '    var kk = sk.slice(32, 64);',
    '    var tr = sk.slice(64, 128);',
    '    var pos = 128;',
    '    var s1 = [];',
    '    for (var i = 0; i < L; i++) { s1.push(mlDsaUnpack3(sk.slice(pos, pos + 96))); pos += 96; }',
    '    var s2 = [];',
    '    for (var i = 0; i < K; i++) { s2.push(mlDsaUnpack3(sk.slice(pos, pos + 96))); pos += 96; }',
    '    var t0 = [];',
    '    for (var i = 0; i < K; i++) { t0.push(mlDsaUnpack13(sk.slice(pos, pos + 416))); pos += 416; }',
    '    return [rho, kk, tr, s1, s2, t0];',
    '  }',
    '  function mlDsaPkEncode(rho, t1) {',
    '    var pk = rho.slice();',
    '    for (var i = 0; i < K; i++) pk = pk.concat(mlDsaPack10Raw(t1[i]));',
    '    return pk;',
    '  }',
    '  function mlDsaPkDecode(pk) {',
    '    var rho = pk.slice(0, 32);',
    '    var t1 = [];',
    '    for (var i = 0; i < K; i++) t1.push(mlDsaUnpack10Raw(pk.slice(32 + 320 * i, 32 + 320 * (i + 1))));',
    '    return [rho, t1];',
    '  }',
    '  function mlDsaSigEncode(ctilde, z, h) {',
    '    var sig = ctilde.slice();',
    '    for (var i = 0; i < L; i++) sig = sig.concat(mlDsaPack18(z[i]));',
    '    sig = sig.concat(mlDsaHintPack(h));',
    '    return sig;',
    '  }',
    '  function mlDsaSigDecode(sig) {',
    '    var ctilde = sig.slice(0, 32);',
    '    var z = [];',
    '    var pos = 32;',
    '    for (var i = 0; i < L; i++) { z.push(mlDsaUnpack18(sig.slice(pos, pos + 576))); pos += 576; }',
    '    var h = mlDsaHintUnpack(sig.slice(pos, pos + OMEGA + K));',
    '    return [ctilde, z, h];',
    '  }',
    '  function mlDsaW1Encode(w1) {',
    '    var out = [];',
    '    for (var r = 0; r < K; r++) out = out.concat(mlDsaPack6Raw(w1[r]));',
    '    return out;',
    '  }',
    '  function mlDsaSignInternal(sk, mprime, rnd) {',
    '    var dec = mlDsaSkDecode(sk);',
    '    var rho = dec[0], Kk = dec[1], tr = dec[2], s1 = dec[3], s2 = dec[4], t0 = dec[5];',
    '    var s1h = [], s2h = [], t0h = [];',
    '    for (var i = 0; i < L; i++) s1h.push(mlDsaNtt(s1[i]));',
    '    for (var i = 0; i < K; i++) { s2h.push(mlDsaNtt(s2[i])); t0h.push(mlDsaNtt(t0[i])); }',
    '    var A = mlDsaExpandA(rho);',
    '    var mu = mlDsaShake(tr.concat(mprime), 64, 136);',
    '    var rhop2 = mlDsaShake(Kk.concat(rnd, mu), 64, 136);',
    '    var kappa = 0;',
    '    var ctilde, z, h;',
    '    while (true) {',
    '      var y = mlDsaExpandMask(rhop2, kappa);',
    '      var yh = [];',
    '      for (var i = 0; i < L; i++) yh.push(mlDsaNtt(y[i]));',
    '      var w = [];',
    '      for (var r = 0; r < K; r++) {',
    '        var acc = new Array(256).fill(0);',
    '        for (var s = 0; s < L; s++) {',
    '          var pr = mlDsaMulNtt(A[r][s], yh[s]);',
    '          for (var j = 0; j < 256; j++) acc[j] = mlDsaMod(acc[j] + pr[j]);',
    '        }',
    '        w.push(mlDsaIntt(acc));',
    '      }',
    '      var w1 = [];',
    '      var w1enc = [];',
    '      for (var r = 0; r < K; r++) {',
    '        var row = [];',
    '        for (var j = 0; j < 256; j++) row.push(mlDsaHighBits(w[r][j]));',
    '        w1.push(row);',
    '        w1enc = w1enc.concat(mlDsaPack6Raw(row));',
    '      }',
    '      ctilde = mlDsaShake(mu.concat(w1enc), CTILDE_LEN, 136);',
    '      var c = mlDsaSampleInBall(ctilde);',
    '      var ch = mlDsaNtt(c);',
    '      var cs1 = [];',
    '      for (var i = 0; i < L; i++) cs1.push(mlDsaIntt(mlDsaMulNtt(ch, s1h[i])));',
    '      z = [];',
    '      var zmax = 0;',
    '      for (var i = 0; i < L; i++) {',
    '        var zp = [];',
    '        for (var j = 0; j < 256; j++) {',
    '          var zv = mlDsaCentered(y[i][j] + cs1[i][j]);',
    '          zp.push(zv);',
    '          if (zv < 0 ? -zv > zmax : zv > zmax) zmax = zv < 0 ? -zv : zv;',
    '        }',
    '        z.push(zp);',
    '      }',
    '      var cs2 = [];',
    '      for (var i = 0; i < K; i++) cs2.push(mlDsaIntt(mlDsaMulNtt(ch, s2h[i])));',
    '      var r0 = [];',
    '      var r0max = 0;',
    '      for (var r = 0; r < K; r++) {',
    '        var r0p = [];',
    '        for (var j = 0; j < 256; j++) {',
    '          var lv = mlDsaLowBits(mlDsaMod(w[r][j] - cs2[r][j]));',
    '          r0p.push(lv);',
    '          if (lv < 0 ? -lv > r0max : lv > r0max) r0max = lv < 0 ? -lv : lv;',
    '        }',
    '        r0.push(r0p);',
    '      }',
    '      if (zmax >= GAMMA1 - BETA || r0max >= GAMMA2 - BETA) { kappa += L; continue; }',
    '      var ct0 = [];',
    '      for (var i = 0; i < K; i++) ct0.push(mlDsaIntt(mlDsaMulNtt(ch, t0h[i])));',
    '      h = [];',
    '      var weight = 0;',
    '      var ct0max = 0;',
    '      for (var r = 0; r < K; r++) {',
    '        var hr = [];',
    '        for (var j = 0; j < 256; j++) {',
    '          var ct = mlDsaCentered(ct0[r][j]);',
    '          if (ct < 0 ? -ct > ct0max : ct > ct0max) ct0max = ct < 0 ? -ct : ct;',
    '          var base = mlDsaMod(w[r][j] - cs2[r][j] + ct0[r][j]);',
    '          var bit = mlDsaMakeHint(mlDsaMod(-ct), base);',
    '          hr.push(bit);',
    '          weight += bit;',
    '        }',
    '        h.push(hr);',
    '      }',
    '      if (ct0max >= GAMMA2 || weight > OMEGA) { kappa += L; continue; }',
    '      break;',
    '    }',
    '    return mlDsaSigEncode(ctilde, z, h);',
    '  }',
    '  function mlDsaSign(sk, message, ctx, rnd) {',
    '    if (ctx === undefined || ctx === null) ctx = [];',
    '    if (rnd === undefined || rnd === null) rnd = new Array(32).fill(0);',
    '    var mprime = [0x00, ctx.length].concat(ctx, message);',
    '    return mlDsaSignInternal(sk, mprime, rnd);',
    '  }',
    '  function mlDsaVerifyInternal(pk, mprime, sig) {',
    '    var dec = mlDsaPkDecode(pk);',
    '    var rho = dec[0], t1 = dec[1];',
    '    var sdec = mlDsaSigDecode(sig);',
    '    var ctilde = sdec[0], z = sdec[1], h = sdec[2];',
    '    if (h === null) return false;',
    '    var weight = 0;',
    '    for (var r = 0; r < K; r++) for (var j = 0; j < 256; j++) weight += h[r][j];',
    '    if (weight > OMEGA) return false;',
    '    var A = mlDsaExpandA(rho);',
    '    var tr = mlDsaShake(pk, 64, 136);',
    '    var mu = mlDsaShake(tr.concat(mprime), 64, 136);',
    '    var c = mlDsaSampleInBall(ctilde);',
    '    var ch = mlDsaNtt(c);',
    '    var zh = [];',
    '    for (var i = 0; i < L; i++) zh.push(mlDsaNtt(z[i]));',
    '    var t1h = [];',
    '    for (var r = 0; r < K; r++) t1h.push(mlDsaNtt(t1[r]));',
    '    var wapprox = [];',
    '    for (var r = 0; r < K; r++) {',
    '      var acc = new Array(256).fill(0);',
    '      for (var s = 0; s < L; s++) {',
    '        var pr = mlDsaMulNtt(A[r][s], zh[s]);',
    '        for (var j = 0; j < 256; j++) acc[j] = mlDsaMod(acc[j] + pr[j]);',
    '      }',
    '      var t2d = new Array(256);',
    '      for (var j = 0; j < 256; j++) t2d[j] = (t1h[r][j] * Math.pow(2, D)) % Q; // 2^d * NTT(t1); avoid 32-bit shift wrap',
    '      var pr2 = mlDsaMulNtt(ch, t2d);',
    '      for (var j = 0; j < 256; j++) acc[j] = mlDsaMod(acc[j] - pr2[j]);',
    '      wapprox.push(mlDsaIntt(acc));',
    '    }',
    '    var w1 = [];',
    '    var w1enc = [];',
    '    for (var r = 0; r < K; r++) {',
    '      var row = [];',
    '      for (var j = 0; j < 256; j++) row.push(mlDsaUseHint(h[r][j], wapprox[r][j]));',
    '      w1.push(row);',
    '      w1enc = w1enc.concat(mlDsaPack6Raw(row));',
    '    }',
    '    var ctilde2 = mlDsaShake(mu.concat(w1enc), CTILDE_LEN, 136);',
    '    var zmax = 0;',
    '    for (var i = 0; i < L; i++) {',
    '      for (var j = 0; j < 256; j++) {',
    '        var zv = z[i][j] < 0 ? -z[i][j] : z[i][j];',
    '        if (zv > zmax) zmax = zv;',
    '      }',
    '    }',
    '    var match = true;',
    '    for (var i = 0; i < CTILDE_LEN; i++) if (ctilde2[i] !== ctilde[i]) { match = false; break; }',
    '    return match && zmax < GAMMA1 - BETA;',
    '  }',
    '  function mlDsaVerify(pk, message, sig, ctx) {',
    '    if (ctx === undefined || ctx === null) ctx = [];',
    '    var mprime = [0x00, ctx.length].concat(ctx, message);',
    '    return mlDsaVerifyInternal(pk, mprime, sig);',
    '  }',
    '  function mlDsaPkFromSk(sk) {',
    '    var dec = mlDsaSkDecode(sk);',
    '    var rho = dec[0], s1 = dec[3], s2 = dec[4];',
    '    var A = mlDsaExpandA(rho);',
    '    var s1h = [];',
    '    for (var i = 0; i < L; i++) s1h.push(mlDsaNtt(s1[i]));',
    '    var t = [];',
    '    for (var r = 0; r < K; r++) {',
    '      var acc = new Array(256).fill(0);',
    '      for (var s = 0; s < L; s++) {',
    '        var pr = mlDsaMulNtt(A[r][s], s1h[s]);',
    '        for (var j = 0; j < 256; j++) acc[j] = mlDsaMod(acc[j] + pr[j]);',
    '      }',
    '      acc = mlDsaIntt(acc);',
    '      for (var j = 0; j < 256; j++) acc[j] = mlDsaMod(acc[j] + s2[r][j]);',
    '      t.push(acc);',
    '    }',
    '    var t1 = [];',
    '    for (var r = 0; r < K; r++) {',
    '      var row = [];',
    '      for (var j = 0; j < 256; j++) row.push(mlDsaPower2Round(t[r][j])[0]);',
    '      t1.push(row);',
    '    }',
    '    return mlDsaPkEncode(rho, t1);',
    '  }',
    '  var ZETAS = mlDsaZetas();',
    '  return { sign: mlDsaSign, verify: mlDsaVerify, signInternal: mlDsaSignInternal, verifyInternal: mlDsaVerifyInternal, pkFromSk: mlDsaPkFromSk };',
    '}',
  ]);
}

/** 公共签名入口：mlDsaSign(sk, message, ctx?, rnd?) — 缺省 ctx=[], rnd=0^32（确定性） */
function registerMlDsaSign(): string {
  const core = registerMlDsaCore();
  registerMlDsaSignInternal();
  registerMlDsaVerifyInternal();
  registerMlDsaPkFromSk();
  return javascriptGenerator.provideFunction_('mlDsaSign', [
    'function ' + javascriptGenerator.FUNCTION_NAME_PLACEHOLDER_ + '(sk, message, ctx, rnd) {',
    '  return ' + core + '().sign(sk, message, ctx, rnd);',
    '}',
  ]);
}

/** 公共验签入口：mlDsaVerify(pk, message, sig, ctx?) */
function registerMlDsaVerify(): string {
  const core = registerMlDsaCore();
  registerMlDsaSignInternal();
  registerMlDsaVerifyInternal();
  return javascriptGenerator.provideFunction_('mlDsaVerify', [
    'function ' + javascriptGenerator.FUNCTION_NAME_PLACEHOLDER_ + '(pk, message, sig, ctx) {',
    '  return ' + core + '().verify(pk, message, sig, ctx);',
    '}',
  ]);
}

/** 公钥派生（测试/demo 用）：mlDsaPkFromSk(sk) */
function registerMlDsaPkFromSk(): string {
  const core = registerMlDsaCore();
  return javascriptGenerator.provideFunction_('mlDsaPkFromSk', [
    'function ' + javascriptGenerator.FUNCTION_NAME_PLACEHOLDER_ + '(sk) {',
    '  return ' + core + '().pkFromSk(sk);',
    '}',
  ]);
}

/** 内部接口签名（ACVP internal 测试用）：mlDsaSignInternal(sk, mprime, rnd) */
function registerMlDsaSignInternal(): string {
  const core = registerMlDsaCore();
  return javascriptGenerator.provideFunction_('mlDsaSignInternal', [
    'function ' + javascriptGenerator.FUNCTION_NAME_PLACEHOLDER_ + '(sk, mprime, rnd) {',
    '  return ' + core + '().signInternal(sk, mprime, rnd);',
    '}',
  ]);
}

/** 内部接口验签（ACVP internal 测试用）：mlDsaVerifyInternal(pk, mprime, sig) */
function registerMlDsaVerifyInternal(): string {
  const core = registerMlDsaCore();
  return javascriptGenerator.provideFunction_('mlDsaVerifyInternal', [
    'function ' + javascriptGenerator.FUNCTION_NAME_PLACEHOLDER_ + '(pk, mprime, sig) {',
    '  return ' + core + '().verifyInternal(pk, mprime, sig);',
    '}',
  ]);
}

javascriptGenerator.forBlock['mldsa_sign'] = function (block: Block): [string, number] {
  const sk = javascriptGenerator.valueToCode(block, 'SECRET_KEY', Order.ATOMIC) || '[]';
  const msg = javascriptGenerator.valueToCode(block, 'MESSAGE', Order.ATOMIC) || '[]';
  const fn = registerMlDsaSign();
  return [fn + '(' + sk + ', ' + msg + ')', Order.ATOMIC];
};

javascriptGenerator.forBlock['mldsa_verify'] = function (block: Block): [string, number] {
  const pk = javascriptGenerator.valueToCode(block, 'PUBLIC_KEY', Order.ATOMIC) || '[]';
  const msg = javascriptGenerator.valueToCode(block, 'MESSAGE', Order.ATOMIC) || '[]';
  const sig = javascriptGenerator.valueToCode(block, 'SIGNATURE', Order.ATOMIC) || '[]';
  const fn = registerMlDsaVerify();
  return [fn + '(' + pk + ', ' + msg + ', ' + sig + ')', Order.ATOMIC];
};
