/**
 * Argon2 原子块 Python 代码生成器 (RFC 9106 v1.3)
 *
 * 内嵌完整 Argon2d/i/id：纯 Python BLAKE2b（RFC 7693，无 hashlib 依赖）、H' 变长哈希、
 * G 压缩函数（BLAKE2b 轮 + 2·trunc 乘法）、索引函数（Argon2i/id 数据无关段 =
 * H0 派生预计算伪随机地址）。官方向量 RFC 9106 §5.1-5.3 全 PASS。
 */
import { pythonGenerator, Order } from 'blockly/python';
import type { Block } from 'blockly/core';

/** 完整 Argon2（含内嵌 BLAKE2b），返回 tagLen 字节（bytes） */
function registerArgon2(): string {
  return pythonGenerator.provideFunction_('argon2_hash', [
    'def ' + pythonGenerator.FUNCTION_NAME_PLACEHOLDER_ + '(pwd, salt, secret, ad, m_cost, t_cost, lanes, tag_len, variant):',
    '    M64 = (1 << 64) - 1',
    '    M32 = (1 << 32) - 1',
    '    IV = [0x6a09e667f3bcc908,0xbb67ae8584caa73b,0x3c6ef372fe94f82b,0xa54ff53a5f1d36f1,0x510e527fade682d1,0x9b05688c2b3e6c1f,0x1f83d9abfb41bd6b,0x5be0cd19137e2179]',
    '    SIGMA = [[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],[14,10,4,8,9,15,13,6,1,12,0,2,11,7,5,3],[11,8,12,0,5,2,15,13,10,14,3,6,7,1,9,4],[7,9,3,1,13,12,11,14,2,6,5,10,4,0,15,8],[9,0,5,7,2,4,10,15,14,1,11,12,6,8,3,13],[2,12,6,10,0,11,8,3,4,13,7,5,15,14,1,9],[12,5,1,15,14,13,4,10,0,7,6,3,9,2,8,11],[13,11,7,14,12,1,3,9,5,0,15,4,8,6,2,10],[6,15,14,9,11,3,0,8,12,2,13,7,1,4,10,5],[10,2,8,4,7,6,1,5,15,11,9,14,3,12,13,0],[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],[14,10,4,8,9,15,13,6,1,12,0,2,11,7,5,3]]',
    '    def rotr64(x, n):',
    '        return ((x >> n) | (x << (64 - n))) & M64',
    '    def blake2b_g(v, a, b, c, d, x, y):',
    '        v[a] = (v[a] + v[b] + x) & M64',
    '        v[d] = rotr64(v[d] ^ v[a], 32)',
    '        v[c] = (v[c] + v[d]) & M64',
    '        v[b] = rotr64(v[b] ^ v[c], 24)',
    '        v[a] = (v[a] + v[b] + y) & M64',
    '        v[d] = rotr64(v[d] ^ v[a], 16)',
    '        v[c] = (v[c] + v[d]) & M64',
    '        v[b] = rotr64(v[b] ^ v[c], 63)',
    '    def blake2b_hash(data, out_len):',
    '        if isinstance(data, str):',
    '            data = data.encode("utf-8")',
    '        data = bytes(data)',
    '        h = list(IV)',
    '        h[0] ^= 0x01010000 ^ out_len',
    '        n = len(data)',
    '        nb = (n + 127) // 128',
    '        if nb == 0:',
    '            nb = 1',
    '        for bi in range(nb):',
    '            block = data[bi * 128:(bi + 1) * 128]',
    '            if len(block) < 128:',
    '                block = block + bytes(128 - len(block))',
    '            is_final = (bi == nb - 1)',
    '            t = n if is_final else (bi + 1) * 128',
    '            v = h + list(IV)',
    '            v[12] ^= t & M64',
    '            v[13] ^= (t >> 64) & M64',
    '            if is_final:',
    '                v[14] ^= M64',
    '            m = [int.from_bytes(block[i * 8:(i + 1) * 8], "little") for i in range(16)]',
    '            for r in range(12):',
    '                s = SIGMA[r]',
    '                blake2b_g(v,0,4,8,12,m[s[0]],m[s[1]])',
    '                blake2b_g(v,1,5,9,13,m[s[2]],m[s[3]])',
    '                blake2b_g(v,2,6,10,14,m[s[4]],m[s[5]])',
    '                blake2b_g(v,3,7,11,15,m[s[6]],m[s[7]])',
    '                blake2b_g(v,0,5,10,15,m[s[8]],m[s[9]])',
    '                blake2b_g(v,1,6,11,12,m[s[10]],m[s[11]])',
    '                blake2b_g(v,2,7,8,13,m[s[12]],m[s[13]])',
    '                blake2b_g(v,3,4,9,14,m[s[14]],m[s[15]])',
    '            for i in range(8):',
    '                h[i] ^= v[i] ^ v[i + 8]',
    '        out = bytearray()',
    '        for w in h:',
    '            out += w.to_bytes(8, "little")',
    '        return bytes(out[:out_len])',
    '    def le32(x):',
    '        return (x & 0xFFFFFFFF).to_bytes(4, "little")',
    '    def blake2b_long(out_len, data):',
    '        if isinstance(data, str):',
    '            data = data.encode("utf-8")',
    '        data = bytes(data)',
    '        if out_len <= 64:',
    '            return blake2b_hash(le32(out_len) + data, out_len)',
    '        r = (out_len + 31) // 32 - 2',
    '        v = blake2b_hash(le32(out_len) + data, 64)',
    '        out = bytearray(v[:32])',
    '        for _ in range(r - 1):',
    '            v = blake2b_hash(v, 64)',
    '            out += v[:32]',
    '        v = blake2b_hash(v, 64)',
    '        out += v[:out_len - 32 * r]',
    '        return bytes(out)',
    '    def load_block(data):',
    '        return [int.from_bytes(data[i * 8:(i + 1) * 8], "little") for i in range(128)]',
    '    def blamka_g(v, a, b, c, d):',
    '        v[a] = (v[a] + v[b] + 2 * (v[a] & M32) * (v[b] & M32)) & M64',
    '        v[d] = rotr64(v[d] ^ v[a], 32)',
    '        v[c] = (v[c] + v[d] + 2 * (v[c] & M32) * (v[d] & M32)) & M64',
    '        v[b] = rotr64(v[b] ^ v[c], 24)',
    '        v[a] = (v[a] + v[b] + 2 * (v[a] & M32) * (v[b] & M32)) & M64',
    '        v[d] = rotr64(v[d] ^ v[a], 16)',
    '        v[c] = (v[c] + v[d] + 2 * (v[c] & M32) * (v[d] & M32)) & M64',
    '        v[b] = rotr64(v[b] ^ v[c], 63)',
    '    def blake_round_no_msg(w):',
    '        blamka_g(w,0,4,8,12)',
    '        blamka_g(w,1,5,9,13)',
    '        blamka_g(w,2,6,10,14)',
    '        blamka_g(w,3,7,11,15)',
    '        blamka_g(w,0,5,10,15)',
    '        blamka_g(w,1,6,11,12)',
    '        blamka_g(w,2,7,8,13)',
    '        blamka_g(w,3,4,9,14)',
    '    def fill_block(prev, ref, old=None):',
    '        R = [prev[i] ^ ref[i] for i in range(128)]',
    '        r0 = R[:]',
    '        for i in range(8):',
    '            off = 16 * i',
    '            w = R[off:off + 16]',
    '            blake_round_no_msg(w)',
    '            R[off:off + 16] = w',
    '        for i in range(8):',
    '            idx = [2 * i + 16 * k + j for k in range(8) for j in range(2)]',
    '            w = [R[x] for x in idx]',
    '            blake_round_no_msg(w)',
    '            for x, val in zip(idx, w):',
    '                R[x] = val',
    '        if old is None:',
    '            return [r0[i] ^ R[i] for i in range(128)]',
    '        return [(r0[i] ^ R[i] ^ old[i]) & M64 for i in range(128)]',
    '    def index_alpha(pass_num, slice_num, index, same_lane, pseudo_rand32, lane_length, seg_len):',
    '        if pass_num == 0:',
    '            if slice_num == 0:',
    '                ref_area = index - 1',
    '            elif same_lane:',
    '                ref_area = slice_num * seg_len + index - 1',
    '            else:',
    '                ref_area = slice_num * seg_len + (-1 if index == 0 else 0)',
    '        else:',
    '            if same_lane:',
    '                ref_area = lane_length - seg_len + index - 1',
    '            else:',
    '                ref_area = lane_length - seg_len + (-1 if index == 0 else 0)',
    '        rel = (pseudo_rand32 * pseudo_rand32) >> 32',
    '        rel = ref_area - 1 - ((ref_area * rel) >> 32)',
    '        start = 0',
    '        if pass_num > 0:',
    '            start = 0 if slice_num == 3 else (slice_num + 1) * seg_len',
    '        return (start + rel) % lane_length',
    '    def fill_segment(memory, pass_num, lane, slice_num, lanes, lane_length, seg_len, block_count, t_cost, y):',
    '        dia = (y == 1) or (y == 2 and pass_num == 0 and slice_num < 2)',
    '        with_xor = pass_num > 0',
    '        start_idx = 2 if (pass_num == 0 and slice_num == 0) else 0',
    '        zero = [0] * 128',
    '        addr = None',
    '        if dia:',
    '            input_block = [0] * 128',
    '            input_block[0] = pass_num',
    '            input_block[1] = lane',
    '            input_block[2] = slice_num',
    '            input_block[3] = block_count',
    '            input_block[4] = t_cost',
    '            input_block[5] = y',
    '            if pass_num == 0 and slice_num == 0:',
    '                input_block[6] = 1',
    '                addr = fill_block(zero, fill_block(zero, input_block))',
    '        for i in range(start_idx, seg_len):',
    '            j = slice_num * seg_len + i',
    '            prev = memory[lane * lane_length + ((j - 1 + lane_length) % lane_length)]',
    '            if dia:',
    '                if i % 128 == 0:',
    '                    input_block[6] += 1',
    '                    addr = fill_block(zero, fill_block(zero, input_block))',
    '                pseudo = addr[i % 128]',
    '            else:',
    '                pseudo = prev[0]',
    '            ref_lane = (pseudo >> 32) % lanes',
    '            if pass_num == 0 and slice_num == 0:',
    '                ref_lane = lane',
    '            ref_idx = index_alpha(pass_num, slice_num, i, ref_lane == lane, pseudo & M32, lane_length, seg_len)',
    '            ref = memory[ref_lane * lane_length + ref_idx]',
    '            cur = lane * lane_length + j',
    '            old = memory[cur] if with_xor else None',
    '            memory[cur] = fill_block(prev, ref, old)',
    '    if isinstance(pwd, str):',
    '        pwd = pwd.encode("utf-8")',
    '    if isinstance(salt, str):',
    '        salt = salt.encode("utf-8")',
    '    if isinstance(secret, str):',
    '        secret = secret.encode("utf-8")',
    '    if isinstance(ad, str):',
    '        ad = ad.encode("utf-8")',
    '    pwd = bytes(pwd or [])',
    '    salt = bytes(salt or [])',
    '    secret = bytes(secret or [])',
    '    ad = bytes(ad or [])',
    '    m_cost = int(m_cost)',
    '    t_cost = int(t_cost)',
    '    lanes = int(lanes)',
    '    tag_len = int(tag_len)',
    '    y = int(variant)',
    '    version = 19',
    '    block_count = 4 * lanes * (m_cost // (4 * lanes))',
    '    lane_length = block_count // lanes',
    '    seg_len = lane_length // 4',
    '    h0 = blake2b_hash(le32(lanes) + le32(tag_len) + le32(m_cost) + le32(t_cost) + le32(version) + le32(y) + le32(len(pwd)) + pwd + le32(len(salt)) + salt + le32(len(secret)) + secret + le32(len(ad)) + ad, 64)',
    '    memory = [None] * block_count',
    '    for l in range(lanes):',
    '        memory[l * lane_length + 0] = load_block(blake2b_long(1024, h0 + le32(0) + le32(l)))',
    '        memory[l * lane_length + 1] = load_block(blake2b_long(1024, h0 + le32(1) + le32(l)))',
    '    for r in range(t_cost):',
    '        for s in range(4):',
    '            for l in range(lanes):',
    '                fill_segment(memory, r, l, s, lanes, lane_length, seg_len, block_count, t_cost, y)',
    '    C = memory[lane_length - 1][:]',
    '    for l in range(1, lanes):',
    '        last = memory[l * lane_length + lane_length - 1]',
    '        C = [C[i] ^ last[i] for i in range(128)]',
    '    return blake2b_long(tag_len, b"".join(w.to_bytes(8, "little") for w in C))',
  ]);
}

pythonGenerator.forBlock['argon2_hash'] = function (block: Block): [string, number] {
  const pwd = pythonGenerator.valueToCode(block, 'PASSWORD', Order.ATOMIC) || '[]';
  const salt = pythonGenerator.valueToCode(block, 'SALT', Order.ATOMIC) || '[]';
  const secret = pythonGenerator.valueToCode(block, 'SECRET', Order.ATOMIC) || '[]';
  const ad = pythonGenerator.valueToCode(block, 'AD', Order.ATOMIC) || '[]';
  const mCost = pythonGenerator.valueToCode(block, 'M_COST', Order.ATOMIC) || '32';
  const tCost = pythonGenerator.valueToCode(block, 'T_COST', Order.ATOMIC) || '3';
  const lanes = pythonGenerator.valueToCode(block, 'LANES', Order.ATOMIC) || '4';
  const tagLen = pythonGenerator.valueToCode(block, 'TAGLEN', Order.ATOMIC) || '32';
  const variant = block.getFieldValue('VARIANT') || '2';
  const fn = registerArgon2();
  return [
    fn + '(' + pwd + ', ' + salt + ', ' + secret + ', ' + ad + ', ' + mCost + ', ' + tCost + ', ' + lanes + ', ' + tagLen + ', ' + variant + ')',
    Order.ATOMIC,
  ];
};
