/**
 * Argon2 原子块 JavaScript 代码生成器 (RFC 9106 v1.3)
 *
 * 内嵌完整 Argon2d/i/id：BLAKE2b（RFC 7693，BigInt 64 位字，无 WebCrypto 依赖）、
 * H' 变长哈希、G 压缩函数（BLAKE2b 轮 + 2·trunc 乘法）、索引函数（Argon2i/id
 * 数据无关段 = H0 派生预计算伪随机地址）。官方向量 RFC 9106 §5.1-5.3 全 PASS。
 */
import { javascriptGenerator, Order } from 'blockly/javascript';
import type { Block } from 'blockly/core';

/** 完整 Argon2（含内嵌 BLAKE2b），返回 tagLen 字节数组 */
function registerArgon2(): string {
  return javascriptGenerator.provideFunction_('argon2Hash', [
    'function ' + javascriptGenerator.FUNCTION_NAME_PLACEHOLDER_ + '(pwd, salt, secret, ad, mCost, tCost, lanes, tagLen, variant) {',
    '  var M64 = 0xFFFFFFFFFFFFFFFFn;',
    '  var M32 = 0xFFFFFFFFn;',
    '  var IV = [0x6a09e667f3bcc908n,0xbb67ae8584caa73bn,0x3c6ef372fe94f82bn,0xa54ff53a5f1d36f1n,0x510e527fade682d1n,0x9b05688c2b3e6c1fn,0x1f83d9abfb41bd6bn,0x5be0cd19137e2179n];',
    '  var SIGMA = [[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],[14,10,4,8,9,15,13,6,1,12,0,2,11,7,5,3],[11,8,12,0,5,2,15,13,10,14,3,6,7,1,9,4],[7,9,3,1,13,12,11,14,2,6,5,10,4,0,15,8],[9,0,5,7,2,4,10,15,14,1,11,12,6,8,3,13],[2,12,6,10,0,11,8,3,4,13,7,5,15,14,1,9],[12,5,1,15,14,13,4,10,0,7,6,3,9,2,8,11],[13,11,7,14,12,1,3,9,5,0,15,4,8,6,2,10],[6,15,14,9,11,3,0,8,12,2,13,7,1,4,10,5],[10,2,8,4,7,6,1,5,15,11,9,14,3,12,13,0],[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],[14,10,4,8,9,15,13,6,1,12,0,2,11,7,5,3]];',
    '  function rotr64(x, n) { return ((x >> BigInt(n)) | (x << BigInt(64 - n))) & M64; }',
    '  function blake2bG(v, a, b, c, d, x, y) {',
    '    v[a] = (v[a] + v[b] + x) & M64; v[d] = rotr64(v[d] ^ v[a], 32);',
    '    v[c] = (v[c] + v[d]) & M64; v[b] = rotr64(v[b] ^ v[c], 24);',
    '    v[a] = (v[a] + v[b] + y) & M64; v[d] = rotr64(v[d] ^ v[a], 16);',
    '    v[c] = (v[c] + v[d]) & M64; v[b] = rotr64(v[b] ^ v[c], 63);',
    '  }',
    '  function blake2bHash(data, outLen) {',
    '    var h = IV.slice();',
    '    h[0] ^= 0x01010000n ^ BigInt(outLen);',
    '    var n = data.length;',
    '    var nb = Math.ceil(n / 128); if (nb === 0) nb = 1;',
    '    for (var bi = 0; bi < nb; bi++) {',
    '      var block = data.slice(bi * 128, (bi + 1) * 128);',
    '      while (block.length < 128) block.push(0);',
    '      var isFinal = bi === nb - 1;',
    '      var t = isFinal ? BigInt(n) : BigInt((bi + 1) * 128);',
    '      var v = h.concat(IV);',
    '      v[12] ^= t & M64; v[13] ^= (t >> 64n) & M64;',
    '      if (isFinal) v[14] ^= M64;',
    '      var m = new Array(16);',
    '      for (var i = 0; i < 16; i++) { var w = 0n; for (var k = 7; k >= 0; k--) w = (w << 8n) | BigInt(block[i * 8 + k]); m[i] = w; }',
    '      for (var r = 0; r < 12; r++) {',
    '        var s = SIGMA[r];',
    '        blake2bG(v,0,4,8,12,m[s[0]],m[s[1]]); blake2bG(v,1,5,9,13,m[s[2]],m[s[3]]);',
    '        blake2bG(v,2,6,10,14,m[s[4]],m[s[5]]); blake2bG(v,3,7,11,15,m[s[6]],m[s[7]]);',
    '        blake2bG(v,0,5,10,15,m[s[8]],m[s[9]]); blake2bG(v,1,6,11,12,m[s[10]],m[s[11]]);',
    '        blake2bG(v,2,7,8,13,m[s[12]],m[s[13]]); blake2bG(v,3,4,9,14,m[s[14]],m[s[15]]);',
    '      }',
    '      for (var i = 0; i < 8; i++) h[i] ^= v[i] ^ v[i + 8];',
    '    }',
    '    var out = [];',
    '    for (var i = 0; i < 8 && out.length < outLen; i++)',
    '      for (var k = 0; k < 8 && out.length < outLen; k++) out.push(Number((h[i] >> BigInt(8 * k)) & 0xFFn));',
    '    return out;',
    '  }',
    '  function le32(x) { return [x & 0xFF, (x >>> 8) & 0xFF, (x >>> 16) & 0xFF, (x >>> 24) & 0xFF]; }',
    '  function blake2bLong(outLen, input) {',
    '    if (outLen <= 64) return blake2bHash(le32(outLen).concat(input), outLen);',
    '    var r = Math.ceil(outLen / 32) - 2;',
    '    var v = blake2bHash(le32(outLen).concat(input), 64);',
    '    var out = v.slice(0, 32);',
    '    for (var i = 2; i <= r; i++) { v = blake2bHash(v, 64); out = out.concat(v.slice(0, 32)); }',
    '    v = blake2bHash(v, 64);',
    '    out = out.concat(v.slice(0, outLen - 32 * r));',
    '    return out;',
    '  }',
    '  function loadBlock(data) {',
    '    var w = new Array(128);',
    '    for (var i = 0; i < 128; i++) { var x = 0n; for (var k = 7; k >= 0; k--) x = (x << 8n) | BigInt(data[i * 8 + k]); w[i] = x; }',
    '    return w;',
    '  }',
    '  function blamkaG(v, a, b, c, d) {',
    '    v[a] = (v[a] + v[b] + 2n * (v[a] & M32) * (v[b] & M32)) & M64; v[d] = rotr64(v[d] ^ v[a], 32);',
    '    v[c] = (v[c] + v[d] + 2n * (v[c] & M32) * (v[d] & M32)) & M64; v[b] = rotr64(v[b] ^ v[c], 24);',
    '    v[a] = (v[a] + v[b] + 2n * (v[a] & M32) * (v[b] & M32)) & M64; v[d] = rotr64(v[d] ^ v[a], 16);',
    '    v[c] = (v[c] + v[d] + 2n * (v[c] & M32) * (v[d] & M32)) & M64; v[b] = rotr64(v[b] ^ v[c], 63);',
    '  }',
    '  function blakeRoundNoMsg(w) {',
    '    blamkaG(w,0,4,8,12); blamkaG(w,1,5,9,13); blamkaG(w,2,6,10,14); blamkaG(w,3,7,11,15);',
    '    blamkaG(w,0,5,10,15); blamkaG(w,1,6,11,12); blamkaG(w,2,7,8,13); blamkaG(w,3,4,9,14);',
    '  }',
    '  function fillBlock(prev, ref, old) {',
    '    var R = new Array(128);',
    '    for (var i = 0; i < 128; i++) R[i] = prev[i] ^ ref[i];',
    '    var r0 = R.slice();',
    '    for (var i = 0; i < 8; i++) { var w = R.slice(16 * i, 16 * i + 16); blakeRoundNoMsg(w); for (var j = 0; j < 16; j++) R[16 * i + j] = w[j]; }',
    '    for (var i = 0; i < 8; i++) {',
    '      var w = new Array(16);',
    '      for (var k = 0; k < 8; k++) { w[2 * k] = R[2 * i + 16 * k]; w[2 * k + 1] = R[2 * i + 16 * k + 1]; }',
    '      blakeRoundNoMsg(w);',
    '      for (var k = 0; k < 8; k++) { R[2 * i + 16 * k] = w[2 * k]; R[2 * i + 16 * k + 1] = w[2 * k + 1]; }',
    '    }',
    '    var res = new Array(128);',
    '    for (var i = 0; i < 128; i++) res[i] = (r0[i] ^ R[i] ^ (old ? old[i] : 0n)) & M64;',
    '    return res;',
    '  }',
    '  function indexAlpha(passNum, sliceNum, index, sameLane, pseudoRand32, laneLength, segLen) {',
    '    var refArea;',
    '    if (passNum === 0) {',
    '      if (sliceNum === 0) refArea = index - 1;',
    '      else if (sameLane) refArea = sliceNum * segLen + index - 1;',
    '      else refArea = sliceNum * segLen + (index === 0 ? -1 : 0);',
    '    } else {',
    '      if (sameLane) refArea = laneLength - segLen + index - 1;',
    '      else refArea = laneLength - segLen + (index === 0 ? -1 : 0);',
    '    }',
    '    var rel = BigInt(pseudoRand32) * BigInt(pseudoRand32) >> 32n;',
    '    rel = BigInt(refArea) - 1n - ((BigInt(refArea) * rel) >> 32n);',
    '    var start = 0n;',
    '    if (passNum > 0) start = sliceNum === 3 ? 0n : BigInt((sliceNum + 1) * segLen);',
    '    return Number((start + rel) % BigInt(laneLength));',
    '  }',
    '  function fillSegment(memory, passNum, lane, sliceNum, lanes, laneLength, segLen, blockCount, tCost, y) {',
    '    var dia = y === 1 || (y === 2 && passNum === 0 && sliceNum < 2);',
    '    var withXor = passNum > 0;',
    '    var startIdx = (passNum === 0 && sliceNum === 0) ? 2 : 0;',
    '    var zero = new Array(128).fill(0n);',
    '    var inputBlock = null, addr = null;',
    '    if (dia) {',
    '      inputBlock = new Array(128).fill(0n);',
    '      inputBlock[0] = BigInt(passNum); inputBlock[1] = BigInt(lane); inputBlock[2] = BigInt(sliceNum);',
    '      inputBlock[3] = BigInt(blockCount); inputBlock[4] = BigInt(tCost); inputBlock[5] = BigInt(y);',
    '      if (passNum === 0 && sliceNum === 0) { inputBlock[6] = 1n; addr = fillBlock(zero, fillBlock(zero, inputBlock)); }',
    '    }',
    '    for (var i = startIdx; i < segLen; i++) {',
    '      var j = sliceNum * segLen + i;',
    '      var prev = memory[lane * laneLength + ((j - 1 + laneLength) % laneLength)];',
    '      var pseudo;',
    '      if (dia) {',
    '        if (i % 128 === 0) { inputBlock[6] += 1n; addr = fillBlock(zero, fillBlock(zero, inputBlock)); }',
    '        pseudo = addr[i % 128];',
    '      } else { pseudo = prev[0]; }',
    '      var refLane = Number(pseudo >> 32n) % lanes;',
    '      if (passNum === 0 && sliceNum === 0) refLane = lane;',
    '      var refIdx = indexAlpha(passNum, sliceNum, i, refLane === lane, Number(pseudo & M32), laneLength, segLen);',
    '      var ref = memory[refLane * laneLength + refIdx];',
    '      var cur = lane * laneLength + j;',
    '      var old = withXor ? memory[cur] : null;',
    '      memory[cur] = fillBlock(prev, ref, old);',
    '    }',
    '  }',
    '  pwd = Array.from(pwd || []); salt = Array.from(salt || []);',
    '  secret = Array.from(secret || []); ad = Array.from(ad || []);',
    '  mCost = Math.floor(Number(mCost)); tCost = Math.floor(Number(tCost));',
    '  lanes = Math.floor(Number(lanes)); tagLen = Math.floor(Number(tagLen));',
    '  variant = Number(variant);',
    '  var y = variant, version = 19;',
    '  var blockCount = 4 * lanes * Math.floor(mCost / (4 * lanes));',
    '  var laneLength = Math.floor(blockCount / lanes);',
    '  var segLen = Math.floor(laneLength / 4);',
    '  var h0 = blake2bHash(le32(lanes).concat(le32(tagLen), le32(mCost), le32(tCost), le32(version), le32(y), le32(pwd.length), pwd, le32(salt.length), salt, le32(secret.length), secret, le32(ad.length), ad), 64);',
    '  var memory = new Array(blockCount);',
    '  for (var l = 0; l < lanes; l++) {',
    '    memory[l * laneLength + 0] = loadBlock(blake2bLong(1024, h0.concat(le32(0), le32(l))));',
    '    memory[l * laneLength + 1] = loadBlock(blake2bLong(1024, h0.concat(le32(1), le32(l))));',
    '  }',
    '  for (var r = 0; r < tCost; r++)',
    '    for (var s = 0; s < 4; s++)',
    '      for (var l = 0; l < lanes; l++)',
    '        fillSegment(memory, r, l, s, lanes, laneLength, segLen, blockCount, tCost, y);',
    '  var C = memory[laneLength - 1].slice();',
    '  for (var l = 1; l < lanes; l++) { var last = memory[l * laneLength + laneLength - 1]; for (var i = 0; i < 128; i++) C[i] ^= last[i]; }',
    '  var tagBytes = [];',
    '  for (var i = 0; i < 128; i++) for (var k = 0; k < 8; k++) tagBytes.push(Number((C[i] >> BigInt(8 * k)) & 0xFFn));',
    '  return blake2bLong(tagLen, tagBytes);',
    '}',
  ]);
}

javascriptGenerator.forBlock['argon2_hash'] = function (block: Block): [string, number] {
  const pwd = javascriptGenerator.valueToCode(block, 'PASSWORD', Order.ATOMIC) || '[]';
  const salt = javascriptGenerator.valueToCode(block, 'SALT', Order.ATOMIC) || '[]';
  const secret = javascriptGenerator.valueToCode(block, 'SECRET', Order.ATOMIC) || '[]';
  const ad = javascriptGenerator.valueToCode(block, 'AD', Order.ATOMIC) || '[]';
  const mCost = javascriptGenerator.valueToCode(block, 'M_COST', Order.ATOMIC) || '32';
  const tCost = javascriptGenerator.valueToCode(block, 'T_COST', Order.ATOMIC) || '3';
  const lanes = javascriptGenerator.valueToCode(block, 'LANES', Order.ATOMIC) || '4';
  const tagLen = javascriptGenerator.valueToCode(block, 'TAGLEN', Order.ATOMIC) || '32';
  const variant = block.getFieldValue('VARIANT') || '2';
  const fn = registerArgon2();
  return [
    fn + '(' + pwd + ', ' + salt + ', ' + secret + ', ' + ad + ', ' + mCost + ', ' + tCost + ', ' + lanes + ', ' + tagLen + ', ' + variant + ')',
    Order.ATOMIC,
  ];
};
