/**
 * Goppa 码 Patterson 译码 Python 生成器（McEliece 编码基，完整算法闭包）
 *
 * 闭包 goppa_core：GF(2^8) AES 域（0x11B）+ 多项式环运算 + 16×16 Frobenius 开方。
 * 算法见块定义头注释；σ = r² + z·B²（余数 r 与 T 系数 B，经 50/50 双错随机验证）。
 */
import { pythonGenerator, Order } from 'blockly/python';
import type { Block } from 'blockly/core';

function registerGoppaCore(): string {
  return pythonGenerator.provideFunction_('goppa_core', [
    'def ' + pythonGenerator.FUNCTION_NAME_PLACEHOLDER_ + '():',
    '    def trim(p):',
    '        p = list(p)',
    '        while len(p) > 1 and p[-1] == 0:',
    '            p.pop()',
    '        return p',
    '    def gf_mul(a, b):',
    '        p = 0',
    '        for _ in range(8):',
    '            if b & 1: p ^= a',
    '            hi = a & 0x80',
    '            a = (a << 1) & 0xFF',
    '            if hi: a ^= 0x1B',
    '            b >>= 1',
    '        return p',
    '    def gf_inv(a):',
    '        if a == 0: return 0',
    '        r = 1',
    '        for bit in bin(254)[2:]:',
    '            r = gf_mul(r, r)',
    '            if bit == "1": r = gf_mul(r, a)',
    '        return r',
    '    def poly_add(a, b):',
    '        out = [0] * max(len(a), len(b))',
    '        for i in range(len(a)): out[i] ^= a[i]',
    '        for i in range(len(b)): out[i] ^= b[i]',
    '        return trim(out)',
    '    def poly_mul(a, b):',
    '        out = [0] * (len(a) + len(b) - 1)',
    '        for i, ai in enumerate(a):',
    '            if ai:',
    '                for j, bj in enumerate(b):',
    '                    if bj:',
    '                        out[i + j] ^= gf_mul(ai, bj)',
    '        return trim(out)',
    '    def poly_divmod(a, b):',
    '        a = trim(a); b = trim(b)',
    '        if len(b) == 1 and b[0] == 0:',
    '            return [0], [0]',
    '        lc_inv = gf_inv(b[-1])',
    '        q = [0] * max(len(a) - len(b) + 1, 0)',
    '        r = a[:]',
    '        while len(r) >= len(b):',
    '            qc = gf_mul(r[-1], lc_inv)',
    '            if qc:',
    '                shift = len(r) - len(b)',
    '                q[shift] = qc',
    '                for i in range(len(b)):',
    '                    r[shift + i] ^= gf_mul(qc, b[i])',
    '            r.pop()',
    '        return trim(q), trim(r if r else [0])',
    '    def poly_mod(a, b):',
    '        return poly_divmod(a, b)[1]',
    '    def poly_xgcd(a, b):',
    '        r0, r1 = trim(a), trim(b)',
    '        s0, s1 = [1], [0]',
    '        t0, t1 = [0], [1]',
    '        while not (len(r1) == 1 and r1[0] == 0):',
    '            q, r = poly_divmod(r0, r1)',
    '            r0, r1 = r1, r',
    '            s0, s1 = s1, poly_add(s0, poly_mul(q, s1))',
    '            t0, t1 = t1, poly_add(t0, poly_mul(q, t1))',
    '        lc = r0[-1]',
    '        if lc != 1:',
    '            inv = gf_inv(lc)',
    '            r0 = [gf_mul(c, inv) for c in r0]',
    '            s0 = [gf_mul(c, inv) for c in s0]',
    '            t0 = [gf_mul(c, inv) for c in t0]',
    '        return [len(s0)] + s0 + [len(t0)] + t0 + r0',
    '    def poly_eval(p, x):',
    '        r = 0',
    '        for c in reversed(trim(p)):',
    '            r = gf_mul(r, x) ^ c',
    '        return r',
    '    def ring_sqrt_mod(u, g):',
    '        # sqrt in GF(2^8)[z]/(g)：16×16 GF(2) Frobenius 矩阵（基 z^i · 2^j）',
    '        t = len(trim(g)) - 1',
    '        n = t * 8',
    '        cols = []',
    '        for i in range(t):',
    '            for j in range(8):',
    '                e = [0] * t',
    '                e[i] = 1 << j',
    '                sq = poly_mod(poly_mul(e, e), g)',
    '                sq = (sq + [0] * t)[:t]',
    '                col = []',
    '                for ii in range(t):',
    '                    c = sq[ii]',
    '                    for jj in range(8):',
    '                        col.append((c >> jj) & 1)',
    '                cols.append(col)',
    '        m = [[cols[l][k] for l in range(n)] for k in range(n)]',
    '        uu = (poly_mod(u, g) + [0] * t)[:t]',
    '        b = []',
    '        for ii in range(t):',
    '            c = uu[ii]',
    '            for jj in range(8):',
    '                b.append((c >> jj) & 1)',
    '        aug = [m[i][:] + [b[i]] for i in range(n)]',
    '        for col in range(n):',
    '            piv = -1',
    '            for r in range(col, n):',
    '                if aug[r][col]:',
    '                    piv = r; break',
    '            if piv < 0:',
    '                return [0]',
    '            if piv != col:',
    '                aug[col], aug[piv] = aug[piv], aug[col]',
    '            for r2 in range(n):',
    '                if r2 != col and aug[r2][col]:',
    '                    for j2 in range(n + 1):',
    '                        aug[r2][j2] ^= aug[col][j2]',
    '        out = [0] * t',
    '        for ii in range(t):',
    '            for jj in range(8):',
    '                out[ii] |= (aug[ii * 8 + jj][n] << jj)',
    '        return trim(out)',
    '    def goppa_decode(y, g, L):',
    '        y = [v & 1 for v in y]',
    '        g = trim(g); L = list(L)',
    '        t = len(g) - 1',
    '        # 1. syndrome S = Σ_{y_i=1} (z−α_i)⁻¹ mod g',
    '        S = [0]',
    '        for i, yi in enumerate(y):',
    '            if yi:',
    '                p = poly_xgcd(poly_mod([L[i], 1], g), g)',
    '                S = poly_add(S, p[1:1 + p[0]])',
    '        S = poly_mod(S, g)',
    '        if trim(S) == [0]:',
    '            return y',
    '        # 2. T = sqrt(z + S⁻¹) mod g',
    '        p = poly_xgcd(S, g)',
    '        sinv = p[1:1 + p[0]]',
    '        T = ring_sqrt_mod(poly_add([0, 1], sinv), g)',
    '        # 3. 扩展欧几里得 (g, T) 至 deg r ≤ ⌊t/2⌋；σ = r² + z·B²',
    '        bound = t // 2',
    '        r0, r1 = g, T',
    '        s0, s1 = [1], [0]',
    '        u0, u1 = [0], [1]',
    '        while len(trim(r1)) - 1 > bound:',
    '            q, r = poly_divmod(r0, r1)',
    '            r0, r1 = r1, r',
    '            s0, s1 = s1, poly_add(s0, poly_mul(q, s1))',
    '            u0, u1 = u1, poly_add(u0, poly_mul(q, u1))',
    '        sigma = poly_add(poly_mul(r1, r1), poly_mul([0, 1], poly_mul(u1, u1)))',
    '        # 4. σ 在 L 中求根 → 翻转',
    '        out = list(y)',
    '        for i, al in enumerate(L):',
    '            if poly_eval(sigma, al) == 0:',
    '                out[i] ^= 1',
    '        return out',
    '    return {"goppa_decode": goppa_decode}',
    '',
  ]);
}

pythonGenerator.forBlock['goppa_decode'] = function (block: Block): [string, number] {
  const y = pythonGenerator.valueToCode(block, 'Y', Order.ATOMIC) || '[]';
  const g = pythonGenerator.valueToCode(block, 'G', Order.ATOMIC) || '[]';
  const L = pythonGenerator.valueToCode(block, 'L', Order.ATOMIC) || '[]';
  const fn = registerGoppaCore();
  return [fn + '()["goppa_decode"](' + y + ', ' + g + ', ' + L + ')', Order.ATOMIC];
};
