/**
 * SM9 数字签名原子块 JavaScript 代码生成器
 * GB/T 38635.2-2020（R-ate pairing，BN 曲线，Fp12 塔域 u²=-2, s³=u, t²=s）
 *
 * 内嵌全套（一次 provideFunction_ 注册去重）：
 *   sm9Sm3/sm9ModInv/sm9H + Fp2/Fp6/Fp12 塔域 + G1/G2 射影点 + 线函数 + sm9Pair
 *   入口 sm9MasterKey/sm9UserKey/sm9Sign/sm9Verify（模块作用域，driver 可直接调用）
 * 官方向量（GB/T 38635.2-2020 附录 A.2：ks=0130E784…/IDA=Alice/hid=01/
 * M="Chinese IBS standard"/r=033c8616…）H/S/verify 全 PASS；与 Go gmsm 输出一致。
 */
import { javascriptGenerator, Order } from 'blockly/javascript';
import type { Block } from 'blockly/core';

/** SM9 全套内嵌函数（常数/塔域/配对/四入口均在模块作用域，driver 可直接调用） */
function registerSm9(): string {
  return javascriptGenerator.provideFunction_('sm9Sign', [
    '',
    '// ---------- constants ----------',
    'var SM9P = 0xb640000002a3a6f1d603ab4ff58ec74521f2934b1a7aeedbe56f9b27e351457dn;',
    'var SM9N = 0xb640000002a3a6f1d603ab4ff58ec74449f2934b18ea8beee56ee19cd69ecf25n;',
    'var SM9P1 = [0x93de051d62bf718ff5ed0704487d01d6e1e4086909dc3280e8c4e4817c66ddddn, 0x21fe8dda4f21e607631065125c395bbc1c1c00cbfa6024350c464cd70a3ea616n, 1n];',
    'var SM9P2 = [[0x85aef3d078640c98597b6027b441a01ff1dd2c190f5e93c454806c11d8806141n, 0x3722755292130b08d2aab97fd34ec120ee265948d19c17abf9b7213baf82d65bn],',
    '             [0x17509b092e845c1266ba0d262cbee6ed0736a96fa347c8bd856dc76b84ebeb96n, 0xa7cf28d519be3da65f3170153d278ff247efba98a71a08116215bba5c999a7c7n],',
    '             [0n, 1n], [0n, 1n]];',
    'var SM9_NAF = [0,-1,0,0,0,0,1,0,1,0,0,-1,0,-1,0,0,0,-1,0,-1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1];',
    'var SM9_B1 = 0xb640000002a3a6f0e303ab4ff2eb2052a9f02115caef75e70f738991676af24an; // beta^{-(p-1)/3}',
    'var SM9_B2 = 0x49db721a269967c4e0a8debc0783182f82555233139e9d63efbd7b54092c756cn; // beta^{-(p-1)/2}',
    'var SM9_B3 = 0xb640000002a3a6f0e303ab4ff2eb2052a9f02115caef75e70f738991676af249n; // beta^{-(p^2-1)/3}',
    'var SM9_B4 = 0xb640000002a3a6f1d603ab4ff58ec74521f2934b1a7aeedbe56f9b27e351457cn; // beta^{-(p^2-1)/2}',
    '',
    '// ---------- SM3 ----------',
    'function sm9Sm3(input) {',
    '  if (typeof input === "string") input = new TextEncoder().encode(input);',
    '  else if (Array.isArray(input)) input = Uint8Array.from(input);',
    '  var IV = [0x7380166f, 0x4914b2b9, 0x172442d7, 0xda8a0600, 0xa96f30bc, 0x163138aa, 0xe38dee4d, 0xb0fb0e4e];',
    '  var P0 = function (x) { return x ^ ((x << 9) | (x >>> 23)) ^ ((x << 17) | (x >>> 15)); };',
    '  var P1 = function (x) { return x ^ ((x << 15) | (x >>> 17)) ^ ((x << 23) | (x >>> 9)); };',
    '  var FF0 = function (x, y, z) { return x ^ y ^ z; };',
    '  var FF1 = function (x, y, z) { return (x & y) | (x & z) | (y & z); };',
    '  var GG0 = function (x, y, z) { return x ^ y ^ z; };',
    '  var GG1 = function (x, y, z) { return (x & y) | (~x & z); };',
    '  var T = [0x79cc4519, 0x7a879d8a];',
    '  var mLen = input.length, mLenBits = mLen * 8;',
    '  var kk = (448 - mLenBits - 1) % 512; if (kk < 0) kk += 512;',
    '  var padded = new Uint8Array(mLen + 1 + Math.floor(kk / 8) + 8);',
    '  padded.set(input); padded[mLen] = 0x80;',
    '  for (var i = 0; i < 4; i++) padded[padded.length - 1 - i] = (mLenBits >>> (8 * i)) & 0xFF;',
    '  var V = IV.slice();',
    '  for (var off = 0; off < padded.length; off += 64) {',
    '    var B = new Array(16);',
    '    for (var j = 0; j < 16; j++) { var bj = off + j * 4; B[j] = ((padded[bj] << 24) | (padded[bj + 1] << 16) | (padded[bj + 2] << 8) | padded[bj + 3]) >>> 0; }',
    '    var W = new Array(68);',
    '    for (var j = 0; j < 16; j++) W[j] = B[j];',
    '    for (var j = 16; j < 68; j++) W[j] = (P1(W[j - 16] ^ W[j - 9] ^ ((W[j - 3] << 15) | (W[j - 3] >>> 17))) ^ ((W[j - 13] << 7) | (W[j - 13] >>> 25)) ^ W[j - 6]) >>> 0;',
    '    var A = V[0], B2 = V[1], C = V[2], D = V[3], E = V[4], F = V[5], G = V[6], H = V[7];',
    '    for (var j = 0; j < 64; j++) {',
    '      var SS1 = (((A << 12) | (A >>> 20)) + E + ((T[j < 16 ? 0 : 1] << j) | (T[j < 16 ? 0 : 1] >>> (32 - j)))) >>> 0;',
    '      SS1 = ((SS1 << 7) | (SS1 >>> 25)) >>> 0;',
    '      var SS2 = (SS1 ^ ((A << 12) | (A >>> 20))) >>> 0;',
    '      var W1 = (W[j] ^ W[j + 4]) >>> 0;',
    '      var TT1, TT2;',
    '      if (j < 16) { TT1 = (FF0(A, B2, C) + D + SS2 + W1) >>> 0; TT2 = (GG0(E, F, G) + H + SS1 + W[j]) >>> 0; }',
    '      else { TT1 = (FF1(A, B2, C) + D + SS2 + W1) >>> 0; TT2 = (GG1(E, F, G) + H + SS1 + W[j]) >>> 0; }',
    '      D = C; C = ((B2 << 9) | (B2 >>> 23)) >>> 0; B2 = A; A = TT1 >>> 0; H = G;',
    '      G = ((F << 19) | (F >>> 13)) >>> 0; F = E; E = P0(TT2) >>> 0;',
    '    }',
    '    V = [(A ^ V[0]) >>> 0, (B2 ^ V[1]) >>> 0, (C ^ V[2]) >>> 0, (D ^ V[3]) >>> 0, (E ^ V[4]) >>> 0, (F ^ V[5]) >>> 0, (G ^ V[6]) >>> 0, (H ^ V[7]) >>> 0];',
    '  }',
    '  var out = [];',
    '  for (var i = 0; i < 8; i++) out.push((V[i] >>> 24) & 0xFF, (V[i] >>> 16) & 0xFF, (V[i] >>> 8) & 0xFF, V[i] & 0xFF);',
    '  return out;',
    '}',
    '',
    '// ---------- mod inverse (extended Euclid, same body as numtheory modInverseBig) ----------',
    'function sm9ModInv(a, m) {',
    '  a = ((a % m) + m) % m;',
    '  let t = 0n, newT = 1n, r = m, newR = a;',
    '  while (newR !== 0n) {',
    '    const q = r / newR;',
    '    const tmpT = newT; newT = t - q * newT; t = tmpT;',
    '    const tmpR = newR; newR = r - q * newR; r = tmpR;',
    '  }',
    '  if (r !== 1n) throw new Error("inverse does not exist");',
    '  if (t < 0n) t += m;',
    '  return t;',
    '}',
    '',
    '// ---------- H1/H2: (raw mod (N-1)) + 1 ----------',
    'function sm9H(z, mode) {',
    '  var ha = [];',
    '  for (var ct = 1; ct <= 2; ct++) {',
    '    ha = ha.concat(sm9Sm3([mode].concat(z, [(ct >>> 24) & 0xFF, (ct >>> 16) & 0xFF, (ct >>> 8) & 0xFF, ct & 0xFF])));',
    '  }',
    '  var v = 0n;',
    '  for (var i = 0; i < 40; i++) v = (v << 8n) | BigInt(ha[i]);',
    '  return (v % (SM9N - 1n)) + 1n;',
    '}',
    '',
    '// ---------- Fp2 / Fp6 / Fp12 (u²=-2, s³=u, t²=s) ----------',
    '// F2 = [a, b] = a·u + b ; F6 = [x, y, z] = x·s² + y·s + z ; F12 = [x, y] = x·t + y',
    'function fpm(x) { x = x % SM9P; if (x < 0n) x += SM9P; return x; }',
    'function f2Add(a, b) { return [fpm(a[0] + b[0]), fpm(a[1] + b[1])]; }',
    'function f2Sub(a, b) { return [fpm(a[0] - b[0]), fpm(a[1] - b[1])]; }',
    'function f2Neg(a) { return [fpm(-a[0]), fpm(-a[1])]; }',
    'function f2Conj(a) { return [fpm(-a[0]), a[1]]; }',
    'function f2Mul(a, b) { return [fpm(a[0] * b[1] + a[1] * b[0]), fpm(a[1] * b[1] - 2n * a[0] * b[0])]; }',
    'function f2MulU1(a) { return [fpm(a[1]), fpm(-2n * a[0])]; }  // a·u',
    'function f2Sqr(a) { return [fpm(2n * a[0] * a[1]), fpm(a[1] * a[1] - 2n * a[0] * a[0])]; }',
    'function f2MulScalar(a, k) { return [fpm(a[0] * k), fpm(a[1] * k)]; }',
    'function f2Inv(a) {',
    '  var t = fpm(2n * a[0] * a[0] + a[1] * a[1]);',
    '  var inv = sm9ModInv(t, SM9P);',
    '  return [fpm(-a[0] * inv), fpm(a[1] * inv)];',
    '}',
    'function f6From(y, z) { return [[0n, 0n], y, z]; }',
    'function f6Add(a, b) { return [f2Add(a[0], b[0]), f2Add(a[1], b[1]), f2Add(a[2], b[2])]; }',
    'function f6Sub(a, b) { return [f2Sub(a[0], b[0]), f2Sub(a[1], b[1]), f2Sub(a[2], b[2])]; }',
    'function f6Mul(a, b) {',
    '  var v0 = f2Mul(a[2], b[2]), v1 = f2Mul(a[1], b[1]), v2 = f2Mul(a[0], b[0]);',
    '  var t = f2Mul(f2Add(a[1], a[0]), f2Add(b[1], b[0]));',
    '  t = f2Sub(f2Sub(t, v1), v2);',
    '  var z = f2Add(f2MulU1(t), v0);',
    '  t = f2Mul(f2Add(a[2], a[1]), f2Add(b[2], b[1]));',
    '  t = f2Sub(f2Sub(t, v0), v1);',
    '  var y = f2Add(t, f2MulU1(v2));',
    '  t = f2Mul(f2Add(a[2], a[0]), f2Add(b[2], b[0]));',
    '  t = f2Sub(f2Add(f2Sub(t, v0), v1), v2);',
    '  return [t, y, z];',
    '}',
    'function f6MulS(a) { return [a[1], a[2], [fpm(a[0][1]), fpm(-2n * a[0][0])]]; }  // (…)·s',
    'function f6MulF2(a, k) { return [f2Mul(a[0], k), f2Mul(a[1], k), f2Mul(a[2], k)]; }',
    'function f6Sqr(a) {',
    '  var v0 = f2Sqr(a[2]), v1 = f2Sqr(a[1]), v2 = f2Sqr(a[0]);',
    '  var t = f2Sqr(f2Add(a[1], a[0]));',
    '  t = f2Sub(f2Sub(t, v1), v2);',
    '  var z = f2Add(f2MulU1(t), v0);',
    '  t = f2Sqr(f2Add(a[2], a[1]));',
    '  t = f2Sub(f2Sub(t, v0), v1);',
    '  var y = f2Add(t, f2MulU1(v2));',
    '  t = f2Sqr(f2Add(a[2], a[0]));',
    '  t = f2Sub(f2Add(f2Sub(t, v0), v1), v2);',
    '  return [t, y, z];',
    '}',
    'function f12Mul(a, b) {',
    '  var v0 = f6Mul(a[1], b[1]), v1 = f6Mul(a[0], b[0]);',
    '  var tx = f6Sub(f6Sub(f6Mul(f6Add(a[0], a[1]), f6Add(b[0], b[1])), v0), v1);',
    '  var ty = f6Add(f6MulS(v1), v0);',
    '  return [tx, ty];',
    '}',
    'function f12Sqr(a) {',
    '  var tcoef = f6Add(f6Mul(a[0], a[1]), f6Mul(a[0], a[1]));',
    '  var cst = f6Add(f6MulS(f6Sqr(a[0])), f6Sqr(a[1]));',
    '  return [tcoef, cst];',
    '}',
    'function f12Pow(a, e) {',
    '  var r = [[[0n, 0n], [0n, 0n], [0n, 0n]], [[0n, 0n], [0n, 0n], [0n, 1n]]]; // 1',
    '  var b = a;',
    '  while (e) {',
    '    if (e & 1n) r = f12Mul(r, b);',
    '    b = f12Sqr(b);',
    '    e >>= 1n;',
    '  }',
    '  return r;',
    '}',
    '',
    '// ---------- G1 (E: y²=x³+5 over Fp, projective) ----------',
    'function g1IsInf(p) { return p[2] === 0n; }',
    'function g1Dbl(a) {',
    '  var t0 = a[1] * a[1] % SM9P;',
    '  var z3 = 8n * t0 % SM9P;',
    '  var t1 = a[1] * a[2] % SM9P;',
    '  var t2 = a[2] * a[2] % SM9P;',
    '  t2 = 15n * t2 % SM9P;',
    '  var x3 = t2 * z3 % SM9P;',
    '  var y3 = (t0 + t2) % SM9P;',
    '  z3 = t1 * z3 % SM9P;',
    '  t2 = 3n * t2 % SM9P;',
    '  t0 = (t0 - t2 + SM9P) % SM9P;',
    '  y3 = t0 * y3 % SM9P;',
    '  y3 = (x3 + y3) % SM9P;',
    '  t1 = a[0] * a[1] % SM9P;',
    '  x3 = t0 * t1 % SM9P;',
    '  x3 = 2n * x3 % SM9P;',
    '  return [x3, y3, z3];',
    '}',
    'function g1Add(a, b) {',
    '  var t0 = a[0] * b[0] % SM9P;',
    '  var t1 = a[1] * b[1] % SM9P;',
    '  var t2 = a[2] * b[2] % SM9P;',
    '  var t3 = (a[0] + a[1]) % SM9P;',
    '  var t4 = (b[0] + b[1]) % SM9P;',
    '  t3 = t3 * t4 % SM9P;',
    '  t4 = (t0 + t1) % SM9P;',
    '  t3 = (t3 - t4 + SM9P) % SM9P;',
    '  t4 = (a[1] + a[2]) % SM9P;',
    '  var x3 = (b[1] + b[2]) % SM9P;',
    '  t4 = t4 * x3 % SM9P;',
    '  x3 = (t1 + t2) % SM9P;',
    '  t4 = (t4 - x3 + SM9P) % SM9P;',
    '  x3 = (a[0] + a[2]) % SM9P;',
    '  var y3 = (b[0] + b[2]) % SM9P;',
    '  x3 = x3 * y3 % SM9P;',
    '  y3 = (t0 + t2) % SM9P;',
    '  y3 = (x3 - y3 + SM9P) % SM9P;',
    '  t0 = 3n * t0 % SM9P;',
    '  t2 = 15n * t2 % SM9P;',
    '  var z3 = (t1 + t2) % SM9P;',
    '  t1 = (t1 - t2 + SM9P) % SM9P;',
    '  y3 = 15n * y3 % SM9P;',
    '  x3 = t4 * y3 % SM9P;',
    '  t2 = t3 * t1 % SM9P;',
    '  x3 = (t2 - x3 + SM9P) % SM9P;',
    '  y3 = y3 * t0 % SM9P;',
    '  t1 = t1 * z3 % SM9P;',
    '  y3 = (t1 + y3) % SM9P;',
    '  t0 = t0 * t3 % SM9P;',
    '  z3 = z3 * t4 % SM9P;',
    '  z3 = (z3 + t0) % SM9P;',
    '  return [x3, y3, z3];',
    '}',
    'function g1Mul(p, k) {',
    '  var r = [0n, 1n, 0n], a = [p[0], p[1], p[2]];',
    '  k = ((k % SM9N) + SM9N) % SM9N;',
    '  while (k) {',
    '    if (k & 1n) r = g1Add(r, a);',
    '    a = g1Dbl(a);',
    '    k >>= 1n;',
    '  }',
    '  return r;',
    '}',
    'function g1Affine(p) {',
    '  if (g1IsInf(p)) return null;',
    '  var zi = sm9ModInv(p[2], SM9P);',
    '  return [p[0] * zi % SM9P, p[1] * zi % SM9P];',
    '}',
    'function g1OnCurve(p) {',
    '  if (g1IsInf(p)) return true;',
    '  return fpm(p[1] * p[1] * p[2] - p[0] * p[0] * p[0] - 5n * p[2] * p[2] * p[2]) === 0n;',
    '}',
    'function g1MarshalRaw(p) {',
    '  var a = g1Affine(p);',
    '  var out = [];',
    '  for (var i = 31; i >= 0; i--) out.push(Number((a[0] >> BigInt(8 * i)) & 0xFFn));',
    '  for (var i = 31; i >= 0; i--) out.push(Number((a[1] >> BigInt(8 * i)) & 0xFFn));',
    '  return out;',
    '}',
    'function g1Marshal(p) { return [4].concat(g1MarshalRaw(p)); }',
    'function g1ParseRaw(b) {',
    '  var x = 0n, y = 0n;',
    '  for (var i = 0; i < 32; i++) x = (x << 8n) | BigInt(b[i]);',
    '  for (var i = 0; i < 32; i++) y = (y << 8n) | BigInt(b[32 + i]);',
    '  return [x, y, 1n];',
    '}',
    '',
    '// ---------- G2 (twist y²=x³+5u over Fp2, projective with t=z²) ----------',
    'function g2Dbl(a) {',
    '  var t0 = f2Sqr(a[1]);',
    '  var z3 = f2Add(t0, t0); z3 = f2Add(z3, z3); z3 = f2Add(z3, z3); // 8·t0',
    '  var t1 = f2Mul(a[1], a[2]);',
    '  var t2 = f2Mul([15n, 0n], f2Sqr(a[2]));   // 15u·Z² (twist b = 5u)',
    '  var x3 = f2Mul(t2, z3);',
    '  var y3 = f2Add(t0, t2);',
    '  z3 = f2Mul(t1, z3);',
    '  t2 = f2MulScalar(t2, 3n);',
    '  t0 = f2Sub(t0, t2);',
    '  y3 = f2Mul(t0, y3);',
    '  y3 = f2Add(x3, y3);',
    '  t1 = f2Mul(a[0], a[1]);',
    '  x3 = f2Add(f2Mul(t0, t1), f2Mul(t0, t1));',
    '  return [x3, y3, z3, f2Sqr(z3)];',
    '}',
    'function g2Add(a, b) {',
    '  var t0 = f2Mul(a[0], b[0]);',
    '  var t1 = f2Mul(a[1], b[1]);',
    '  var t2 = f2Mul(a[2], b[2]);',
    '  var t3 = f2Mul(f2Add(a[0], a[1]), f2Add(b[0], b[1]));',
    '  t3 = f2Sub(f2Sub(t3, t0), t1);',
    '  var t4 = f2Mul(f2Add(a[1], a[2]), f2Add(b[1], b[2]));',
    '  t4 = f2Sub(f2Sub(t4, t1), t2);',
    '  var x3 = f2Mul(f2Add(a[0], a[2]), f2Add(b[0], b[2]));',
    '  x3 = f2Sub(f2Sub(x3, t0), t2);',
    '  t0 = f2MulScalar(t0, 3n);',
    '  t2 = f2Mul([15n, 0n], t2);            // 15u·Z1Z2',
    '  var z3 = f2Add(t1, t2);',
    '  t1 = f2Sub(t1, t2);',
    '  var y3 = f2Mul([15n, 0n], x3);        // 15u·(X1Z2+X2Z1)',
    '  x3 = f2Sub(f2Mul(t3, t1), f2Mul(t4, y3));',
    '  y3 = f2Add(f2Mul(t1, z3), f2Mul(y3, t0));',
    '  t0 = f2Mul(t0, t3);',
    '  z3 = f2Add(f2Mul(z3, t4), t0);',
    '  return [x3, y3, z3, f2Sqr(z3)];',
    '}',
    'function g2Mul(p, k) {',
    '  var r = [[0n, 0n], [0n, 1n], [0n, 0n], [0n, 0n]];',
    '  var a = [p[0], p[1], p[2], p[3]];',
    '  k = ((k % SM9N) + SM9N) % SM9N;',
    '  while (k) {',
    '    if (k & 1n) r = g2Add(r, a);',
    '    a = g2Dbl(a);',
    '    k >>= 1n;',
    '  }',
    '  return r;',
    '}',
    'function g2Affine(p) {',
    '  var x = p[0], y = p[1], z = p[2];',
    '  if (z[0] === 0n && z[1] === 0n) return null;',
    '  var zi = f2Inv(z);',
    '  return [f2Mul(x, zi), f2Mul(y, zi)];',
    '}',
    'function g2MarshalRaw(p) {',
    '  var a = g2Affine(p);',
    '  var out = [];',
    '  // x0‖x1‖y0‖y1, u-coeff first per level',
    '  var c = [a[0][0], a[0][1], a[1][0], a[1][1]];',
    '  for (var k = 0; k < 4; k++) {',
    '    for (var i = 31; i >= 0; i--) out.push(Number((c[k] >> BigInt(8 * i)) & 0xFFn));',
    '  }',
    '  return out;',
    '}',
    'function g2ParseRaw(b) {',
    '  var c = [];',
    '  for (var k = 0; k < 4; k++) {',
    '    var v = 0n;',
    '    for (var i = 0; i < 32; i++) v = (v << 8n) | BigInt(b[k * 32 + i]);',
    '    c.push(v);',
    '  }',
    '  return [[c[0], c[1]], [c[2], c[3]], [0n, 1n], [0n, 1n]];',
    '}',
    '',
    '// ---------- line functions + pairing ----------',
    'function lineAdd(r, p, rOut, q, r2) {',
    '  // r2 = p.y²',
    '  var B = f2Mul(p[0], r[3]);                     // Xp·Zr²',
    '  var D = f2Sub(f2Sub(f2Sqr(f2Add(p[1], r[2])), r2), r[3]);',
    '  D = f2Mul(D, r[3]);                            // 2Yp·Zr³',
    '  var H = f2Sub(B, r[0]);',
    '  var I = f2Sqr(H);',
    '  var E = f2Add(f2Add(I, I), f2Add(I, I));       // 4I',
    '  var J = f2Mul(H, E);',
    '  var L1 = f2Sub(f2Sub(D, r[1]), r[1]);          // 2YpZr³ - 2Yr',
    '  var V = f2Mul(r[0], E);',
    '  rOut[0] = f2Sub(f2Sub(f2Sub(f2Sqr(L1), J), V), V);',
    '  rOut[2] = f2Sub(f2Sub(f2Sqr(f2Add(r[2], H)), r[3]), I);',
    '  var t = f2Mul(f2Sub(V, rOut[0]), L1);',
    '  var t2 = f2Add(f2Mul(r[1], J), f2Mul(r[1], J));',
    '  rOut[1] = f2Sub(t, t2);',
    '  rOut[3] = f2Sqr(rOut[2]);',
    '  t = f2Sub(f2Sub(f2Sqr(f2Add(p[1], rOut[2])), r2), rOut[3]);',
    '  t2 = f2Add(f2Mul(L1, p[0]), f2Mul(L1, p[0]));',
    '  var a = f2Sub(t2, t);',
    '  var c = f2Add(f2MulScalar(rOut[2], q[1]), f2MulScalar(rOut[2], q[1]));',
    '  var b = f2Add(f2MulScalar(f2Neg(L1), q[0]), f2MulScalar(f2Neg(L1), q[0]));',
    '  return [a, b, c];',
    '}',
    'function lineDbl(r, rOut, q) {',
    '  var A = f2Sqr(r[0]);',
    '  var B = f2Sqr(r[1]);',
    '  var C = f2Sqr(B);',
    '  var D = f2Sub(f2Sub(f2Sqr(f2Add(r[0], B)), A), C);',
    '  D = f2Add(D, D);',
    '  var E = f2Add(f2Add(A, A), A);',
    '  var G = f2Sqr(E);',
    '  rOut[0] = f2Sub(f2Sub(G, D), D);',
    '  rOut[2] = f2Sub(f2Sub(f2Sqr(f2Add(r[1], r[2])), B), r[3]);',
    '  var t8 = f2Add(f2Add(f2Add(C, C), f2Add(C, C)), f2Add(f2Add(C, C), f2Add(C, C))); // 8C',
    '  rOut[1] = f2Sub(f2Mul(f2Sub(D, rOut[0]), E), t8);',
    '  rOut[3] = f2Sqr(rOut[2]);',
    '  var t = f2Add(f2Mul(E, r[3]), f2Mul(E, r[3]));',
    '  var b = f2MulScalar(f2Neg(t), q[0]);',
    '  var a = f2Sub(f2Sub(f2Sub(f2Sqr(f2Add(r[0], E)), A), G), f2Add(f2Add(B, B), f2Add(B, B)));',
    '  var c = f2Add(f2MulScalar(f2Mul(rOut[2], r[3]), q[1]), f2MulScalar(f2Mul(rOut[2], r[3]), q[1]));',
    '  return [a, b, c];',
    '}',
    'function mulLineB6(ret, a, b, c) {',
    '  var a2 = f6Mul(ret[1], f6From(b, a));',
    '  var t3 = f6MulS(f6MulF2(ret[0], c));',
    '  var t = f2Add(b, c);',
    '  var t2 = f6From(t, a);',
    '  ret[0] = f6Add(ret[0], ret[1]);',
    '  ret[1] = t3;',
    '  ret[0] = f6Sub(f6Sub(f6Mul(ret[0], t2), a2), ret[1]);',
    '  ret[1] = f6Add(f6MulS(ret[1]), a2);',
    '  return ret;',
    '}',
    'function sm9Pair(Q, P) {',
    '  // e(P, Q) = R-ate pairing; Q ∈ G2 (twist), P ∈ G1 (projective → affine)',
    '  var ret = [[[0n, 0n], [0n, 0n], [0n, 0n]], [[0n, 0n], [0n, 0n], [0n, 1n]]]; // 1',
    '  var aAff = g2Affine(Q);',
    '  var minusA = [aAff[0], f2Neg(aAff[1]), [0n, 1n], [0n, 1n]];',
    '  var bAff = g1Affine(P);                       // (x, y) Fp pair',
    '  var r = [aAff[0], aAff[1], [0n, 1n], [0n, 1n]];',
    '  var r2 = f2Sqr(aAff[1]);',
    '  var newR = [[0n, 0n], [0n, 0n], [0n, 0n], [0n, 0n]];',
    '  var ln;',
    '  for (var i = SM9_NAF.length - 1; i > 0; i--) {',
    '    ln = lineDbl(r, newR, bAff);',
    '    if (i !== SM9_NAF.length - 1) ret = f12Sqr(ret);',
    '    ret = mulLineB6(ret, ln[0], ln[1], ln[2]);',
    '    var tmp = r; r = newR; newR = tmp;',
    '    var d = SM9_NAF[i - 1];',
    '    if (d === 1) { ln = lineAdd(r, aAff, newR, bAff, r2); }',
    '    else if (d === -1) { ln = lineAdd(r, minusA, newR, bAff, r2); }',
    '    else { continue; }',
    '    ret = mulLineB6(ret, ln[0], ln[1], ln[2]);',
    '    tmp = r; r = newR; newR = tmp;',
    '  }',
    '  // Q1 = [p]Q, minusQ2 = -[p²]Q',
    '  var q1 = [f2MulScalar(f2Conj(aAff[0]), SM9_B1), f2MulScalar(f2Conj(aAff[1]), SM9_B2), [0n, 1n], [0n, 1n]];',
    '  var mq2 = [f2MulScalar(aAff[0], SM9_B3), f2MulScalar(f2Neg(aAff[1]), SM9_B4), [0n, 1n], [0n, 1n]];',
    '  r2 = f2Sqr(q1[1]);',
    '  ln = lineAdd(r, q1, newR, bAff, r2);',
    '  ret = mulLineB6(ret, ln[0], ln[1], ln[2]);',
    '  tmp = r; r = newR; newR = tmp;',
    '  r2 = f2Sqr(mq2[1]);',
    '  ln = lineAdd(r, mq2, newR, bAff, r2);',
    '  ret = mulLineB6(ret, ln[0], ln[1], ln[2]);',
    '  // final exponentiation f^((p^12-1)/N)',
    '  return f12Pow(ret, (SM9P ** 12n - 1n) / SM9N);',
    '}',
    'function gtMarshal(f) {',
    '  var out = [];',
    '  // order: (t⁵u, t⁵, t²u, t², t⁴u, t⁴, tu, t, t³u, t³, u, 1) — u-coeff first',
    '  var coeffs = [f[0][0], f[1][1], f[1][0], f[0][2], f[0][1], f[1][2]];',
    '  for (var k = 0; k < 6; k++) {',
    '    for (var i = 31; i >= 0; i--) out.push(Number((coeffs[k][0] >> BigInt(8 * i)) & 0xFFn));',
    '    for (var i = 31; i >= 0; i--) out.push(Number((coeffs[k][1] >> BigInt(8 * i)) & 0xFFn));',
    '  }',
    '  return out;',
    '}',
    '',
    '// ---------- SM9 blocks ----------',
    'function sm9MasterKey(ks) {',
    '  if (ks.length !== 32) throw new Error("SM9 master key must be 32 bytes");',
    '  var k = 0n;',
    '  for (var i = 0; i < 32; i++) k = (k << 8n) | BigInt(ks[i]);',
    '  return g2MarshalRaw(g2Mul(SM9P2, k));',
    '}',
    'function sm9UserKey(ks, id, hid) {',
    '  if (ks.length !== 32) throw new Error("SM9 master key must be 32 bytes");',
    '  var k = 0n;',
    '  for (var i = 0; i < 32; i++) k = (k << 8n) | BigInt(ks[i]);',
    '  var t1 = sm9H(id.concat([hid]), 1);',
    '  var sum = (t1 + k) % SM9N;',
    '  var t2 = k * sm9ModInv(sum, SM9N) % SM9N;',
    '  return g1MarshalRaw(g1Mul(SM9P1, t2));',
    '}',
    'function ' + javascriptGenerator.FUNCTION_NAME_PLACEHOLDER_ + '(msg, ds, ppub, r) {',
    '  if (ds.length !== 64) throw new Error("SM9 ds must be 64 bytes");',
    '  if (ppub.length !== 128) throw new Error("SM9 Ppub must be 128 bytes");',
    '  if (r.length === 0) {',
    '    r = [];',
    '    for (var i = 0; i < 32; i++) r.push(Math.floor(Math.random() * 256));',
    '  }',
    '  if (r.length !== 32) throw new Error("SM9 r must be 32 bytes or empty");',
    '  var rInt = 0n;',
    '  for (var i = 0; i < 32; i++) rInt = (rInt << 8n) | BigInt(r[i]);',
    '  var g = sm9Pair(g2ParseRaw(ppub), SM9P1);      // e(P1, Ppub)',
    '  var w = f12Pow(g, rInt);',
    '  var h = sm9H(msg.concat(gtMarshal(w)), 2);',
    '  var l = ((rInt - h) % SM9N + SM9N) % SM9N;',
    '  var S = g1Marshal(g1Mul(g1ParseRaw(ds), l));',
    '  var out = [];',
    '  for (var i = 31; i >= 0; i--) out.push(Number((h >> BigInt(8 * i)) & 0xFFn));',
    '  return out.concat(S);',
    '}',
    'function sm9Verify(msg, id, h, s, ppub, hid) {',
    '  if (h.length !== 32) throw new Error("SM9 h must be 32 bytes");',
    '  if (s.length !== 65 || s[0] !== 4) throw new Error("SM9 S must be 65 bytes (0x04 prefix)");',
    '  if (ppub.length !== 128) throw new Error("SM9 Ppub must be 128 bytes");',
    '  var hInt = 0n;',
    '  for (var i = 0; i < 32; i++) hInt = (hInt << 8n) | BigInt(h[i]);',
    '  if (hInt === 0n || hInt >= SM9N) return false;',
    '  var Spt = g1ParseRaw(s.slice(1));',
    '  if (g1IsInf(Spt) || !g1OnCurve(Spt)) return false;',
    '  var t1 = sm9H(id.concat([hid]), 1);',
    '  var Q = g2Add(g2Mul(SM9P2, t1), g2ParseRaw(ppub));',
    '  var g = sm9Pair(g2ParseRaw(ppub), SM9P1);',
    '  var u = sm9Pair(Q, Spt);                        // e(S, Q)',
    '  var w = f12Mul(u, f12Pow(g, hInt));',
    '  var h2 = sm9H(msg.concat(gtMarshal(w)), 2);',
    '  return h2 === hInt;',
    '}',
    '',
  ]);
}

javascriptGenerator.forBlock['sm9_master_key'] = function (block: Block): [string, number] {
  const ks = javascriptGenerator.valueToCode(block, 'KS', Order.ATOMIC) || '[]';
  registerSm9();
  return ['sm9MasterKey(' + ks + ')', Order.ATOMIC];
};

javascriptGenerator.forBlock['sm9_user_key'] = function (block: Block): [string, number] {
  const ks = javascriptGenerator.valueToCode(block, 'KS', Order.ATOMIC) || '[]';
  const id = javascriptGenerator.valueToCode(block, 'ID', Order.ATOMIC) || '[]';
  const hid = block.getFieldValue('HID') || '1';
  registerSm9();
  return ['sm9UserKey(' + ks + ', ' + id + ', ' + hid + ')', Order.ATOMIC];
};

javascriptGenerator.forBlock['sm9_sign'] = function (block: Block): [string, number] {
  const msg = javascriptGenerator.valueToCode(block, 'MSG', Order.ATOMIC) || '[]';
  const ds = javascriptGenerator.valueToCode(block, 'DS', Order.ATOMIC) || '[]';
  const ppub = javascriptGenerator.valueToCode(block, 'PPUB', Order.ATOMIC) || '[]';
  const r = javascriptGenerator.valueToCode(block, 'R', Order.ATOMIC) || '[]';
  registerSm9();
  return ['sm9Sign(' + msg + ', ' + ds + ', ' + ppub + ', ' + r + ')', Order.ATOMIC];
};

javascriptGenerator.forBlock['sm9_verify'] = function (block: Block): [string, number] {
  const msg = javascriptGenerator.valueToCode(block, 'MSG', Order.ATOMIC) || '[]';
  const id = javascriptGenerator.valueToCode(block, 'ID', Order.ATOMIC) || '[]';
  const h = javascriptGenerator.valueToCode(block, 'H', Order.ATOMIC) || '[]';
  const s = javascriptGenerator.valueToCode(block, 'S', Order.ATOMIC) || '[]';
  const ppub = javascriptGenerator.valueToCode(block, 'PPUB', Order.ATOMIC) || '[]';
  const hid = block.getFieldValue('HID') || '1';
  registerSm9();
  return ['sm9Verify(' + msg + ', ' + id + ', ' + h + ', ' + s + ', ' + ppub + ', ' + hid + ')', Order.ATOMIC];
};

